/*
 * Rumble API
 *
 * Rumble Network Discovery API
 *
 * API version: 1.0.4
 * Contact: support@rumble.run
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
)

// Asset struct for Asset
type Asset struct {
	Id string `json:"id"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	SiteId *string `json:"site_id,omitempty"`
	Alive *bool `json:"alive,omitempty"`
	FirstSeen *int64 `json:"first_seen,omitempty"`
	LastSeen *int64 `json:"last_seen,omitempty"`
	DetectedBy *string `json:"detected_by,omitempty"`
	Type *string `json:"type,omitempty"`
	Os *string `json:"os,omitempty"`
	OsVersion *string `json:"os_version,omitempty"`
	Hw *string `json:"hw,omitempty"`
	Addresses *[]string `json:"addresses,omitempty"`
	AddressesExtra *[]string `json:"addresses_extra,omitempty"`
	Macs *[]string `json:"macs,omitempty"`
	MacVendors *[]string `json:"mac_vendors,omitempty"`
	Names *[]string `json:"names,omitempty"`
	Domains *[]string `json:"domains,omitempty"`
	ServiceCount *int64 `json:"service_count,omitempty"`
	ServiceCountTcp *int64 `json:"service_count_tcp,omitempty"`
	ServiceCountUdp *int64 `json:"service_count_udp,omitempty"`
	ServiceCountArp *int64 `json:"service_count_arp,omitempty"`
	ServiceCountIcmp *int64 `json:"service_count_icmp,omitempty"`
	LowestTtl *int64 `json:"lowest_ttl,omitempty"`
	LowestRtt *int64 `json:"lowest_rtt,omitempty"`
	LastAgentId *string `json:"last_agent_id,omitempty"`
	LastTaskId *string `json:"last_task_id,omitempty"`
	NewestMac *string `json:"newest_mac,omitempty"`
	NewestMacVendor *string `json:"newest_mac_vendor,omitempty"`
	NewestMacAge *int64 `json:"newest_mac_age,omitempty"`
	Comments *string `json:"comments,omitempty"`
	ServicePortsTcp *[]string `json:"service_ports_tcp,omitempty"`
	ServicePortsUdp *[]string `json:"service_ports_udp,omitempty"`
	ServicePortsProtocols *[]string `json:"service_ports_protocols,omitempty"`
	ServicePortsProducts *[]string `json:"service_ports_products,omitempty"`
	OrgName *string `json:"org_name,omitempty"`
	SiteName *string `json:"site_name,omitempty"`
	AgentName *string `json:"agent_name,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`
	Services *map[string]map[string]string `json:"services,omitempty"`
	Rtts *map[string]map[string]interface{} `json:"rtts,omitempty"`
	Credentials *map[string]map[string]bool `json:"credentials,omitempty"`
	Attributes *map[string]string `json:"attributes,omitempty"`
}

// NewAsset instantiates a new Asset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAsset(id string, ) *Asset {
	this := Asset{}
	this.Id = id
	return &this
}

// NewAssetWithDefaults instantiates a new Asset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetWithDefaults() *Asset {
	this := Asset{}
	return &this
}

// GetId returns the Id field value
func (o *Asset) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Asset) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Asset) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Asset) GetCreatedAt() int64 {
	if o == nil || o.CreatedAt == nil {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetCreatedAtOk() (*int64, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Asset) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Asset) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Asset) GetUpdatedAt() int64 {
	if o == nil || o.UpdatedAt == nil {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Asset) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Asset) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *Asset) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *Asset) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *Asset) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *Asset) GetSiteId() string {
	if o == nil || o.SiteId == nil {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetSiteIdOk() (*string, bool) {
	if o == nil || o.SiteId == nil {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *Asset) HasSiteId() bool {
	if o != nil && o.SiteId != nil {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *Asset) SetSiteId(v string) {
	o.SiteId = &v
}

// GetAlive returns the Alive field value if set, zero value otherwise.
func (o *Asset) GetAlive() bool {
	if o == nil || o.Alive == nil {
		var ret bool
		return ret
	}
	return *o.Alive
}

// GetAliveOk returns a tuple with the Alive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAliveOk() (*bool, bool) {
	if o == nil || o.Alive == nil {
		return nil, false
	}
	return o.Alive, true
}

// HasAlive returns a boolean if a field has been set.
func (o *Asset) HasAlive() bool {
	if o != nil && o.Alive != nil {
		return true
	}

	return false
}

// SetAlive gets a reference to the given bool and assigns it to the Alive field.
func (o *Asset) SetAlive(v bool) {
	o.Alive = &v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *Asset) GetFirstSeen() int64 {
	if o == nil || o.FirstSeen == nil {
		var ret int64
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetFirstSeenOk() (*int64, bool) {
	if o == nil || o.FirstSeen == nil {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *Asset) HasFirstSeen() bool {
	if o != nil && o.FirstSeen != nil {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given int64 and assigns it to the FirstSeen field.
func (o *Asset) SetFirstSeen(v int64) {
	o.FirstSeen = &v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *Asset) GetLastSeen() int64 {
	if o == nil || o.LastSeen == nil {
		var ret int64
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLastSeenOk() (*int64, bool) {
	if o == nil || o.LastSeen == nil {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *Asset) HasLastSeen() bool {
	if o != nil && o.LastSeen != nil {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given int64 and assigns it to the LastSeen field.
func (o *Asset) SetLastSeen(v int64) {
	o.LastSeen = &v
}

// GetDetectedBy returns the DetectedBy field value if set, zero value otherwise.
func (o *Asset) GetDetectedBy() string {
	if o == nil || o.DetectedBy == nil {
		var ret string
		return ret
	}
	return *o.DetectedBy
}

// GetDetectedByOk returns a tuple with the DetectedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetDetectedByOk() (*string, bool) {
	if o == nil || o.DetectedBy == nil {
		return nil, false
	}
	return o.DetectedBy, true
}

// HasDetectedBy returns a boolean if a field has been set.
func (o *Asset) HasDetectedBy() bool {
	if o != nil && o.DetectedBy != nil {
		return true
	}

	return false
}

// SetDetectedBy gets a reference to the given string and assigns it to the DetectedBy field.
func (o *Asset) SetDetectedBy(v string) {
	o.DetectedBy = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Asset) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Asset) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Asset) SetType(v string) {
	o.Type = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *Asset) GetOs() string {
	if o == nil || o.Os == nil {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetOsOk() (*string, bool) {
	if o == nil || o.Os == nil {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *Asset) HasOs() bool {
	if o != nil && o.Os != nil {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *Asset) SetOs(v string) {
	o.Os = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *Asset) GetOsVersion() string {
	if o == nil || o.OsVersion == nil {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetOsVersionOk() (*string, bool) {
	if o == nil || o.OsVersion == nil {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *Asset) HasOsVersion() bool {
	if o != nil && o.OsVersion != nil {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *Asset) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetHw returns the Hw field value if set, zero value otherwise.
func (o *Asset) GetHw() string {
	if o == nil || o.Hw == nil {
		var ret string
		return ret
	}
	return *o.Hw
}

// GetHwOk returns a tuple with the Hw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetHwOk() (*string, bool) {
	if o == nil || o.Hw == nil {
		return nil, false
	}
	return o.Hw, true
}

// HasHw returns a boolean if a field has been set.
func (o *Asset) HasHw() bool {
	if o != nil && o.Hw != nil {
		return true
	}

	return false
}

// SetHw gets a reference to the given string and assigns it to the Hw field.
func (o *Asset) SetHw(v string) {
	o.Hw = &v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *Asset) GetAddresses() []string {
	if o == nil || o.Addresses == nil {
		var ret []string
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAddressesOk() (*[]string, bool) {
	if o == nil || o.Addresses == nil {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *Asset) HasAddresses() bool {
	if o != nil && o.Addresses != nil {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []string and assigns it to the Addresses field.
func (o *Asset) SetAddresses(v []string) {
	o.Addresses = &v
}

// GetAddressesExtra returns the AddressesExtra field value if set, zero value otherwise.
func (o *Asset) GetAddressesExtra() []string {
	if o == nil || o.AddressesExtra == nil {
		var ret []string
		return ret
	}
	return *o.AddressesExtra
}

// GetAddressesExtraOk returns a tuple with the AddressesExtra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAddressesExtraOk() (*[]string, bool) {
	if o == nil || o.AddressesExtra == nil {
		return nil, false
	}
	return o.AddressesExtra, true
}

// HasAddressesExtra returns a boolean if a field has been set.
func (o *Asset) HasAddressesExtra() bool {
	if o != nil && o.AddressesExtra != nil {
		return true
	}

	return false
}

// SetAddressesExtra gets a reference to the given []string and assigns it to the AddressesExtra field.
func (o *Asset) SetAddressesExtra(v []string) {
	o.AddressesExtra = &v
}

// GetMacs returns the Macs field value if set, zero value otherwise.
func (o *Asset) GetMacs() []string {
	if o == nil || o.Macs == nil {
		var ret []string
		return ret
	}
	return *o.Macs
}

// GetMacsOk returns a tuple with the Macs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetMacsOk() (*[]string, bool) {
	if o == nil || o.Macs == nil {
		return nil, false
	}
	return o.Macs, true
}

// HasMacs returns a boolean if a field has been set.
func (o *Asset) HasMacs() bool {
	if o != nil && o.Macs != nil {
		return true
	}

	return false
}

// SetMacs gets a reference to the given []string and assigns it to the Macs field.
func (o *Asset) SetMacs(v []string) {
	o.Macs = &v
}

// GetMacVendors returns the MacVendors field value if set, zero value otherwise.
func (o *Asset) GetMacVendors() []string {
	if o == nil || o.MacVendors == nil {
		var ret []string
		return ret
	}
	return *o.MacVendors
}

// GetMacVendorsOk returns a tuple with the MacVendors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetMacVendorsOk() (*[]string, bool) {
	if o == nil || o.MacVendors == nil {
		return nil, false
	}
	return o.MacVendors, true
}

// HasMacVendors returns a boolean if a field has been set.
func (o *Asset) HasMacVendors() bool {
	if o != nil && o.MacVendors != nil {
		return true
	}

	return false
}

// SetMacVendors gets a reference to the given []string and assigns it to the MacVendors field.
func (o *Asset) SetMacVendors(v []string) {
	o.MacVendors = &v
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *Asset) GetNames() []string {
	if o == nil || o.Names == nil {
		var ret []string
		return ret
	}
	return *o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetNamesOk() (*[]string, bool) {
	if o == nil || o.Names == nil {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *Asset) HasNames() bool {
	if o != nil && o.Names != nil {
		return true
	}

	return false
}

// SetNames gets a reference to the given []string and assigns it to the Names field.
func (o *Asset) SetNames(v []string) {
	o.Names = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *Asset) GetDomains() []string {
	if o == nil || o.Domains == nil {
		var ret []string
		return ret
	}
	return *o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetDomainsOk() (*[]string, bool) {
	if o == nil || o.Domains == nil {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *Asset) HasDomains() bool {
	if o != nil && o.Domains != nil {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *Asset) SetDomains(v []string) {
	o.Domains = &v
}

// GetServiceCount returns the ServiceCount field value if set, zero value otherwise.
func (o *Asset) GetServiceCount() int64 {
	if o == nil || o.ServiceCount == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCount
}

// GetServiceCountOk returns a tuple with the ServiceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServiceCountOk() (*int64, bool) {
	if o == nil || o.ServiceCount == nil {
		return nil, false
	}
	return o.ServiceCount, true
}

// HasServiceCount returns a boolean if a field has been set.
func (o *Asset) HasServiceCount() bool {
	if o != nil && o.ServiceCount != nil {
		return true
	}

	return false
}

// SetServiceCount gets a reference to the given int64 and assigns it to the ServiceCount field.
func (o *Asset) SetServiceCount(v int64) {
	o.ServiceCount = &v
}

// GetServiceCountTcp returns the ServiceCountTcp field value if set, zero value otherwise.
func (o *Asset) GetServiceCountTcp() int64 {
	if o == nil || o.ServiceCountTcp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountTcp
}

// GetServiceCountTcpOk returns a tuple with the ServiceCountTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServiceCountTcpOk() (*int64, bool) {
	if o == nil || o.ServiceCountTcp == nil {
		return nil, false
	}
	return o.ServiceCountTcp, true
}

// HasServiceCountTcp returns a boolean if a field has been set.
func (o *Asset) HasServiceCountTcp() bool {
	if o != nil && o.ServiceCountTcp != nil {
		return true
	}

	return false
}

// SetServiceCountTcp gets a reference to the given int64 and assigns it to the ServiceCountTcp field.
func (o *Asset) SetServiceCountTcp(v int64) {
	o.ServiceCountTcp = &v
}

// GetServiceCountUdp returns the ServiceCountUdp field value if set, zero value otherwise.
func (o *Asset) GetServiceCountUdp() int64 {
	if o == nil || o.ServiceCountUdp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountUdp
}

// GetServiceCountUdpOk returns a tuple with the ServiceCountUdp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServiceCountUdpOk() (*int64, bool) {
	if o == nil || o.ServiceCountUdp == nil {
		return nil, false
	}
	return o.ServiceCountUdp, true
}

// HasServiceCountUdp returns a boolean if a field has been set.
func (o *Asset) HasServiceCountUdp() bool {
	if o != nil && o.ServiceCountUdp != nil {
		return true
	}

	return false
}

// SetServiceCountUdp gets a reference to the given int64 and assigns it to the ServiceCountUdp field.
func (o *Asset) SetServiceCountUdp(v int64) {
	o.ServiceCountUdp = &v
}

// GetServiceCountArp returns the ServiceCountArp field value if set, zero value otherwise.
func (o *Asset) GetServiceCountArp() int64 {
	if o == nil || o.ServiceCountArp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountArp
}

// GetServiceCountArpOk returns a tuple with the ServiceCountArp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServiceCountArpOk() (*int64, bool) {
	if o == nil || o.ServiceCountArp == nil {
		return nil, false
	}
	return o.ServiceCountArp, true
}

// HasServiceCountArp returns a boolean if a field has been set.
func (o *Asset) HasServiceCountArp() bool {
	if o != nil && o.ServiceCountArp != nil {
		return true
	}

	return false
}

// SetServiceCountArp gets a reference to the given int64 and assigns it to the ServiceCountArp field.
func (o *Asset) SetServiceCountArp(v int64) {
	o.ServiceCountArp = &v
}

// GetServiceCountIcmp returns the ServiceCountIcmp field value if set, zero value otherwise.
func (o *Asset) GetServiceCountIcmp() int64 {
	if o == nil || o.ServiceCountIcmp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountIcmp
}

// GetServiceCountIcmpOk returns a tuple with the ServiceCountIcmp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServiceCountIcmpOk() (*int64, bool) {
	if o == nil || o.ServiceCountIcmp == nil {
		return nil, false
	}
	return o.ServiceCountIcmp, true
}

// HasServiceCountIcmp returns a boolean if a field has been set.
func (o *Asset) HasServiceCountIcmp() bool {
	if o != nil && o.ServiceCountIcmp != nil {
		return true
	}

	return false
}

// SetServiceCountIcmp gets a reference to the given int64 and assigns it to the ServiceCountIcmp field.
func (o *Asset) SetServiceCountIcmp(v int64) {
	o.ServiceCountIcmp = &v
}

// GetLowestTtl returns the LowestTtl field value if set, zero value otherwise.
func (o *Asset) GetLowestTtl() int64 {
	if o == nil || o.LowestTtl == nil {
		var ret int64
		return ret
	}
	return *o.LowestTtl
}

// GetLowestTtlOk returns a tuple with the LowestTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLowestTtlOk() (*int64, bool) {
	if o == nil || o.LowestTtl == nil {
		return nil, false
	}
	return o.LowestTtl, true
}

// HasLowestTtl returns a boolean if a field has been set.
func (o *Asset) HasLowestTtl() bool {
	if o != nil && o.LowestTtl != nil {
		return true
	}

	return false
}

// SetLowestTtl gets a reference to the given int64 and assigns it to the LowestTtl field.
func (o *Asset) SetLowestTtl(v int64) {
	o.LowestTtl = &v
}

// GetLowestRtt returns the LowestRtt field value if set, zero value otherwise.
func (o *Asset) GetLowestRtt() int64 {
	if o == nil || o.LowestRtt == nil {
		var ret int64
		return ret
	}
	return *o.LowestRtt
}

// GetLowestRttOk returns a tuple with the LowestRtt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLowestRttOk() (*int64, bool) {
	if o == nil || o.LowestRtt == nil {
		return nil, false
	}
	return o.LowestRtt, true
}

// HasLowestRtt returns a boolean if a field has been set.
func (o *Asset) HasLowestRtt() bool {
	if o != nil && o.LowestRtt != nil {
		return true
	}

	return false
}

// SetLowestRtt gets a reference to the given int64 and assigns it to the LowestRtt field.
func (o *Asset) SetLowestRtt(v int64) {
	o.LowestRtt = &v
}

// GetLastAgentId returns the LastAgentId field value if set, zero value otherwise.
func (o *Asset) GetLastAgentId() string {
	if o == nil || o.LastAgentId == nil {
		var ret string
		return ret
	}
	return *o.LastAgentId
}

// GetLastAgentIdOk returns a tuple with the LastAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLastAgentIdOk() (*string, bool) {
	if o == nil || o.LastAgentId == nil {
		return nil, false
	}
	return o.LastAgentId, true
}

// HasLastAgentId returns a boolean if a field has been set.
func (o *Asset) HasLastAgentId() bool {
	if o != nil && o.LastAgentId != nil {
		return true
	}

	return false
}

// SetLastAgentId gets a reference to the given string and assigns it to the LastAgentId field.
func (o *Asset) SetLastAgentId(v string) {
	o.LastAgentId = &v
}

// GetLastTaskId returns the LastTaskId field value if set, zero value otherwise.
func (o *Asset) GetLastTaskId() string {
	if o == nil || o.LastTaskId == nil {
		var ret string
		return ret
	}
	return *o.LastTaskId
}

// GetLastTaskIdOk returns a tuple with the LastTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLastTaskIdOk() (*string, bool) {
	if o == nil || o.LastTaskId == nil {
		return nil, false
	}
	return o.LastTaskId, true
}

// HasLastTaskId returns a boolean if a field has been set.
func (o *Asset) HasLastTaskId() bool {
	if o != nil && o.LastTaskId != nil {
		return true
	}

	return false
}

// SetLastTaskId gets a reference to the given string and assigns it to the LastTaskId field.
func (o *Asset) SetLastTaskId(v string) {
	o.LastTaskId = &v
}

// GetNewestMac returns the NewestMac field value if set, zero value otherwise.
func (o *Asset) GetNewestMac() string {
	if o == nil || o.NewestMac == nil {
		var ret string
		return ret
	}
	return *o.NewestMac
}

// GetNewestMacOk returns a tuple with the NewestMac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetNewestMacOk() (*string, bool) {
	if o == nil || o.NewestMac == nil {
		return nil, false
	}
	return o.NewestMac, true
}

// HasNewestMac returns a boolean if a field has been set.
func (o *Asset) HasNewestMac() bool {
	if o != nil && o.NewestMac != nil {
		return true
	}

	return false
}

// SetNewestMac gets a reference to the given string and assigns it to the NewestMac field.
func (o *Asset) SetNewestMac(v string) {
	o.NewestMac = &v
}

// GetNewestMacVendor returns the NewestMacVendor field value if set, zero value otherwise.
func (o *Asset) GetNewestMacVendor() string {
	if o == nil || o.NewestMacVendor == nil {
		var ret string
		return ret
	}
	return *o.NewestMacVendor
}

// GetNewestMacVendorOk returns a tuple with the NewestMacVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetNewestMacVendorOk() (*string, bool) {
	if o == nil || o.NewestMacVendor == nil {
		return nil, false
	}
	return o.NewestMacVendor, true
}

// HasNewestMacVendor returns a boolean if a field has been set.
func (o *Asset) HasNewestMacVendor() bool {
	if o != nil && o.NewestMacVendor != nil {
		return true
	}

	return false
}

// SetNewestMacVendor gets a reference to the given string and assigns it to the NewestMacVendor field.
func (o *Asset) SetNewestMacVendor(v string) {
	o.NewestMacVendor = &v
}

// GetNewestMacAge returns the NewestMacAge field value if set, zero value otherwise.
func (o *Asset) GetNewestMacAge() int64 {
	if o == nil || o.NewestMacAge == nil {
		var ret int64
		return ret
	}
	return *o.NewestMacAge
}

// GetNewestMacAgeOk returns a tuple with the NewestMacAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetNewestMacAgeOk() (*int64, bool) {
	if o == nil || o.NewestMacAge == nil {
		return nil, false
	}
	return o.NewestMacAge, true
}

// HasNewestMacAge returns a boolean if a field has been set.
func (o *Asset) HasNewestMacAge() bool {
	if o != nil && o.NewestMacAge != nil {
		return true
	}

	return false
}

// SetNewestMacAge gets a reference to the given int64 and assigns it to the NewestMacAge field.
func (o *Asset) SetNewestMacAge(v int64) {
	o.NewestMacAge = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *Asset) GetComments() string {
	if o == nil || o.Comments == nil {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetCommentsOk() (*string, bool) {
	if o == nil || o.Comments == nil {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *Asset) HasComments() bool {
	if o != nil && o.Comments != nil {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *Asset) SetComments(v string) {
	o.Comments = &v
}

// GetServicePortsTcp returns the ServicePortsTcp field value if set, zero value otherwise.
func (o *Asset) GetServicePortsTcp() []string {
	if o == nil || o.ServicePortsTcp == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsTcp
}

// GetServicePortsTcpOk returns a tuple with the ServicePortsTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServicePortsTcpOk() (*[]string, bool) {
	if o == nil || o.ServicePortsTcp == nil {
		return nil, false
	}
	return o.ServicePortsTcp, true
}

// HasServicePortsTcp returns a boolean if a field has been set.
func (o *Asset) HasServicePortsTcp() bool {
	if o != nil && o.ServicePortsTcp != nil {
		return true
	}

	return false
}

// SetServicePortsTcp gets a reference to the given []string and assigns it to the ServicePortsTcp field.
func (o *Asset) SetServicePortsTcp(v []string) {
	o.ServicePortsTcp = &v
}

// GetServicePortsUdp returns the ServicePortsUdp field value if set, zero value otherwise.
func (o *Asset) GetServicePortsUdp() []string {
	if o == nil || o.ServicePortsUdp == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsUdp
}

// GetServicePortsUdpOk returns a tuple with the ServicePortsUdp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServicePortsUdpOk() (*[]string, bool) {
	if o == nil || o.ServicePortsUdp == nil {
		return nil, false
	}
	return o.ServicePortsUdp, true
}

// HasServicePortsUdp returns a boolean if a field has been set.
func (o *Asset) HasServicePortsUdp() bool {
	if o != nil && o.ServicePortsUdp != nil {
		return true
	}

	return false
}

// SetServicePortsUdp gets a reference to the given []string and assigns it to the ServicePortsUdp field.
func (o *Asset) SetServicePortsUdp(v []string) {
	o.ServicePortsUdp = &v
}

// GetServicePortsProtocols returns the ServicePortsProtocols field value if set, zero value otherwise.
func (o *Asset) GetServicePortsProtocols() []string {
	if o == nil || o.ServicePortsProtocols == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsProtocols
}

// GetServicePortsProtocolsOk returns a tuple with the ServicePortsProtocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServicePortsProtocolsOk() (*[]string, bool) {
	if o == nil || o.ServicePortsProtocols == nil {
		return nil, false
	}
	return o.ServicePortsProtocols, true
}

// HasServicePortsProtocols returns a boolean if a field has been set.
func (o *Asset) HasServicePortsProtocols() bool {
	if o != nil && o.ServicePortsProtocols != nil {
		return true
	}

	return false
}

// SetServicePortsProtocols gets a reference to the given []string and assigns it to the ServicePortsProtocols field.
func (o *Asset) SetServicePortsProtocols(v []string) {
	o.ServicePortsProtocols = &v
}

// GetServicePortsProducts returns the ServicePortsProducts field value if set, zero value otherwise.
func (o *Asset) GetServicePortsProducts() []string {
	if o == nil || o.ServicePortsProducts == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsProducts
}

// GetServicePortsProductsOk returns a tuple with the ServicePortsProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServicePortsProductsOk() (*[]string, bool) {
	if o == nil || o.ServicePortsProducts == nil {
		return nil, false
	}
	return o.ServicePortsProducts, true
}

// HasServicePortsProducts returns a boolean if a field has been set.
func (o *Asset) HasServicePortsProducts() bool {
	if o != nil && o.ServicePortsProducts != nil {
		return true
	}

	return false
}

// SetServicePortsProducts gets a reference to the given []string and assigns it to the ServicePortsProducts field.
func (o *Asset) SetServicePortsProducts(v []string) {
	o.ServicePortsProducts = &v
}

// GetOrgName returns the OrgName field value if set, zero value otherwise.
func (o *Asset) GetOrgName() string {
	if o == nil || o.OrgName == nil {
		var ret string
		return ret
	}
	return *o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetOrgNameOk() (*string, bool) {
	if o == nil || o.OrgName == nil {
		return nil, false
	}
	return o.OrgName, true
}

// HasOrgName returns a boolean if a field has been set.
func (o *Asset) HasOrgName() bool {
	if o != nil && o.OrgName != nil {
		return true
	}

	return false
}

// SetOrgName gets a reference to the given string and assigns it to the OrgName field.
func (o *Asset) SetOrgName(v string) {
	o.OrgName = &v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *Asset) GetSiteName() string {
	if o == nil || o.SiteName == nil {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetSiteNameOk() (*string, bool) {
	if o == nil || o.SiteName == nil {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *Asset) HasSiteName() bool {
	if o != nil && o.SiteName != nil {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *Asset) SetSiteName(v string) {
	o.SiteName = &v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *Asset) GetAgentName() string {
	if o == nil || o.AgentName == nil {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAgentNameOk() (*string, bool) {
	if o == nil || o.AgentName == nil {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *Asset) HasAgentName() bool {
	if o != nil && o.AgentName != nil {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *Asset) SetAgentName(v string) {
	o.AgentName = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Asset) GetTags() map[string]string {
	if o == nil || o.Tags == nil {
		var ret map[string]string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetTagsOk() (*map[string]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Asset) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]string and assigns it to the Tags field.
func (o *Asset) SetTags(v map[string]string) {
	o.Tags = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *Asset) GetServices() map[string]map[string]string {
	if o == nil || o.Services == nil {
		var ret map[string]map[string]string
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetServicesOk() (*map[string]map[string]string, bool) {
	if o == nil || o.Services == nil {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *Asset) HasServices() bool {
	if o != nil && o.Services != nil {
		return true
	}

	return false
}

// SetServices gets a reference to the given map[string]map[string]string and assigns it to the Services field.
func (o *Asset) SetServices(v map[string]map[string]string) {
	o.Services = &v
}

// GetRtts returns the Rtts field value if set, zero value otherwise.
func (o *Asset) GetRtts() map[string]map[string]interface{} {
	if o == nil || o.Rtts == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.Rtts
}

// GetRttsOk returns a tuple with the Rtts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetRttsOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || o.Rtts == nil {
		return nil, false
	}
	return o.Rtts, true
}

// HasRtts returns a boolean if a field has been set.
func (o *Asset) HasRtts() bool {
	if o != nil && o.Rtts != nil {
		return true
	}

	return false
}

// SetRtts gets a reference to the given map[string]map[string]interface{} and assigns it to the Rtts field.
func (o *Asset) SetRtts(v map[string]map[string]interface{}) {
	o.Rtts = &v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *Asset) GetCredentials() map[string]map[string]bool {
	if o == nil || o.Credentials == nil {
		var ret map[string]map[string]bool
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetCredentialsOk() (*map[string]map[string]bool, bool) {
	if o == nil || o.Credentials == nil {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *Asset) HasCredentials() bool {
	if o != nil && o.Credentials != nil {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given map[string]map[string]bool and assigns it to the Credentials field.
func (o *Asset) SetCredentials(v map[string]map[string]bool) {
	o.Credentials = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Asset) GetAttributes() map[string]string {
	if o == nil || o.Attributes == nil {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Asset) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *Asset) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

func (o Asset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.OrganizationId != nil {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if o.SiteId != nil {
		toSerialize["site_id"] = o.SiteId
	}
	if o.Alive != nil {
		toSerialize["alive"] = o.Alive
	}
	if o.FirstSeen != nil {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if o.LastSeen != nil {
		toSerialize["last_seen"] = o.LastSeen
	}
	if o.DetectedBy != nil {
		toSerialize["detected_by"] = o.DetectedBy
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Os != nil {
		toSerialize["os"] = o.Os
	}
	if o.OsVersion != nil {
		toSerialize["os_version"] = o.OsVersion
	}
	if o.Hw != nil {
		toSerialize["hw"] = o.Hw
	}
	if o.Addresses != nil {
		toSerialize["addresses"] = o.Addresses
	}
	if o.AddressesExtra != nil {
		toSerialize["addresses_extra"] = o.AddressesExtra
	}
	if o.Macs != nil {
		toSerialize["macs"] = o.Macs
	}
	if o.MacVendors != nil {
		toSerialize["mac_vendors"] = o.MacVendors
	}
	if o.Names != nil {
		toSerialize["names"] = o.Names
	}
	if o.Domains != nil {
		toSerialize["domains"] = o.Domains
	}
	if o.ServiceCount != nil {
		toSerialize["service_count"] = o.ServiceCount
	}
	if o.ServiceCountTcp != nil {
		toSerialize["service_count_tcp"] = o.ServiceCountTcp
	}
	if o.ServiceCountUdp != nil {
		toSerialize["service_count_udp"] = o.ServiceCountUdp
	}
	if o.ServiceCountArp != nil {
		toSerialize["service_count_arp"] = o.ServiceCountArp
	}
	if o.ServiceCountIcmp != nil {
		toSerialize["service_count_icmp"] = o.ServiceCountIcmp
	}
	if o.LowestTtl != nil {
		toSerialize["lowest_ttl"] = o.LowestTtl
	}
	if o.LowestRtt != nil {
		toSerialize["lowest_rtt"] = o.LowestRtt
	}
	if o.LastAgentId != nil {
		toSerialize["last_agent_id"] = o.LastAgentId
	}
	if o.LastTaskId != nil {
		toSerialize["last_task_id"] = o.LastTaskId
	}
	if o.NewestMac != nil {
		toSerialize["newest_mac"] = o.NewestMac
	}
	if o.NewestMacVendor != nil {
		toSerialize["newest_mac_vendor"] = o.NewestMacVendor
	}
	if o.NewestMacAge != nil {
		toSerialize["newest_mac_age"] = o.NewestMacAge
	}
	if o.Comments != nil {
		toSerialize["comments"] = o.Comments
	}
	if o.ServicePortsTcp != nil {
		toSerialize["service_ports_tcp"] = o.ServicePortsTcp
	}
	if o.ServicePortsUdp != nil {
		toSerialize["service_ports_udp"] = o.ServicePortsUdp
	}
	if o.ServicePortsProtocols != nil {
		toSerialize["service_ports_protocols"] = o.ServicePortsProtocols
	}
	if o.ServicePortsProducts != nil {
		toSerialize["service_ports_products"] = o.ServicePortsProducts
	}
	if o.OrgName != nil {
		toSerialize["org_name"] = o.OrgName
	}
	if o.SiteName != nil {
		toSerialize["site_name"] = o.SiteName
	}
	if o.AgentName != nil {
		toSerialize["agent_name"] = o.AgentName
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	if o.Rtts != nil {
		toSerialize["rtts"] = o.Rtts
	}
	if o.Credentials != nil {
		toSerialize["credentials"] = o.Credentials
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableAsset struct {
	value *Asset
	isSet bool
}

func (v NullableAsset) Get() *Asset {
	return v.value
}

func (v *NullableAsset) Set(val *Asset) {
	v.value = val
	v.isSet = true
}

func (v NullableAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAsset(val *Asset) *NullableAsset {
	return &NullableAsset{value: val, isSet: true}
}

func (v NullableAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
