/*
 * Rumble API
 *
 * Rumble Network Discovery API
 *
 * API version: 1.0.4
 * Contact: support@rumble.run
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
)

// Service struct for Service
type Service struct {
	ServiceId string `json:"service_id"`
	ServiceAssetId *string `json:"service_asset_id,omitempty"`
	ServiceCreatedAt *int64 `json:"service_created_at,omitempty"`
	ServiceUpdatedAt *int64 `json:"service_updated_at,omitempty"`
	ServiceAddress *string `json:"service_address,omitempty"`
	ServiceTransport *string `json:"service_transport,omitempty"`
	ServiceVhost *string `json:"service_vhost,omitempty"`
	ServicePort *string `json:"service_port,omitempty"`
	ServiceData *map[string]string `json:"service_data,omitempty"`
	ServiceProtocol *string `json:"service_protocol,omitempty"`
	ServiceSummary *string `json:"service_summary,omitempty"`
	ServiceScreenshotLink *string `json:"service_screenshot_link,omitempty"`
	ServiceLink *string `json:"service_link,omitempty"`
	Id string `json:"id"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	SiteId *string `json:"site_id,omitempty"`
	Alive *bool `json:"alive,omitempty"`
	FirstSeen *int64 `json:"first_seen,omitempty"`
	LastSeen *int64 `json:"last_seen,omitempty"`
	DetectedBy *string `json:"detected_by,omitempty"`
	Type *string `json:"type,omitempty"`
	Os *string `json:"os,omitempty"`
	OsVersion *string `json:"os_version,omitempty"`
	Hw *string `json:"hw,omitempty"`
	Addresses *[]string `json:"addresses,omitempty"`
	AddressesExtra *[]string `json:"addresses_extra,omitempty"`
	Macs *[]string `json:"macs,omitempty"`
	MacVendors *[]string `json:"mac_vendors,omitempty"`
	Names *[]string `json:"names,omitempty"`
	Domains *[]string `json:"domains,omitempty"`
	ServiceCount *int64 `json:"service_count,omitempty"`
	ServiceCountTcp *int64 `json:"service_count_tcp,omitempty"`
	ServiceCountUdp *int64 `json:"service_count_udp,omitempty"`
	ServiceCountArp *int64 `json:"service_count_arp,omitempty"`
	ServiceCountIcmp *int64 `json:"service_count_icmp,omitempty"`
	LowestTtl *int64 `json:"lowest_ttl,omitempty"`
	LowestRtt *int64 `json:"lowest_rtt,omitempty"`
	LastAgentId *string `json:"last_agent_id,omitempty"`
	LastTaskId *string `json:"last_task_id,omitempty"`
	NewestMac *string `json:"newest_mac,omitempty"`
	NewestMacVendor *string `json:"newest_mac_vendor,omitempty"`
	NewestMacAge *int64 `json:"newest_mac_age,omitempty"`
	Comments *string `json:"comments,omitempty"`
	ServicePortsTcp *[]string `json:"service_ports_tcp,omitempty"`
	ServicePortsUdp *[]string `json:"service_ports_udp,omitempty"`
	ServicePortsProtocols *[]string `json:"service_ports_protocols,omitempty"`
	ServicePortsProducts *[]string `json:"service_ports_products,omitempty"`
	OrgName *string `json:"org_name,omitempty"`
	SiteName *string `json:"site_name,omitempty"`
	AgentName *string `json:"agent_name,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`
	Services *map[string]map[string]string `json:"services,omitempty"`
	Rtts *map[string]map[string]interface{} `json:"rtts,omitempty"`
	Credentials *map[string]map[string]bool `json:"credentials,omitempty"`
	Attributes *map[string]string `json:"attributes,omitempty"`
}

// NewService instantiates a new Service object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewService(serviceId string, id string, ) *Service {
	this := Service{}
	this.ServiceId = serviceId
	this.Id = id
	return &this
}

// NewServiceWithDefaults instantiates a new Service object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceWithDefaults() *Service {
	this := Service{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *Service) GetServiceId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *Service) GetServiceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *Service) SetServiceId(v string) {
	o.ServiceId = v
}

// GetServiceAssetId returns the ServiceAssetId field value if set, zero value otherwise.
func (o *Service) GetServiceAssetId() string {
	if o == nil || o.ServiceAssetId == nil {
		var ret string
		return ret
	}
	return *o.ServiceAssetId
}

// GetServiceAssetIdOk returns a tuple with the ServiceAssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceAssetIdOk() (*string, bool) {
	if o == nil || o.ServiceAssetId == nil {
		return nil, false
	}
	return o.ServiceAssetId, true
}

// HasServiceAssetId returns a boolean if a field has been set.
func (o *Service) HasServiceAssetId() bool {
	if o != nil && o.ServiceAssetId != nil {
		return true
	}

	return false
}

// SetServiceAssetId gets a reference to the given string and assigns it to the ServiceAssetId field.
func (o *Service) SetServiceAssetId(v string) {
	o.ServiceAssetId = &v
}

// GetServiceCreatedAt returns the ServiceCreatedAt field value if set, zero value otherwise.
func (o *Service) GetServiceCreatedAt() int64 {
	if o == nil || o.ServiceCreatedAt == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCreatedAt
}

// GetServiceCreatedAtOk returns a tuple with the ServiceCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceCreatedAtOk() (*int64, bool) {
	if o == nil || o.ServiceCreatedAt == nil {
		return nil, false
	}
	return o.ServiceCreatedAt, true
}

// HasServiceCreatedAt returns a boolean if a field has been set.
func (o *Service) HasServiceCreatedAt() bool {
	if o != nil && o.ServiceCreatedAt != nil {
		return true
	}

	return false
}

// SetServiceCreatedAt gets a reference to the given int64 and assigns it to the ServiceCreatedAt field.
func (o *Service) SetServiceCreatedAt(v int64) {
	o.ServiceCreatedAt = &v
}

// GetServiceUpdatedAt returns the ServiceUpdatedAt field value if set, zero value otherwise.
func (o *Service) GetServiceUpdatedAt() int64 {
	if o == nil || o.ServiceUpdatedAt == nil {
		var ret int64
		return ret
	}
	return *o.ServiceUpdatedAt
}

// GetServiceUpdatedAtOk returns a tuple with the ServiceUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceUpdatedAtOk() (*int64, bool) {
	if o == nil || o.ServiceUpdatedAt == nil {
		return nil, false
	}
	return o.ServiceUpdatedAt, true
}

// HasServiceUpdatedAt returns a boolean if a field has been set.
func (o *Service) HasServiceUpdatedAt() bool {
	if o != nil && o.ServiceUpdatedAt != nil {
		return true
	}

	return false
}

// SetServiceUpdatedAt gets a reference to the given int64 and assigns it to the ServiceUpdatedAt field.
func (o *Service) SetServiceUpdatedAt(v int64) {
	o.ServiceUpdatedAt = &v
}

// GetServiceAddress returns the ServiceAddress field value if set, zero value otherwise.
func (o *Service) GetServiceAddress() string {
	if o == nil || o.ServiceAddress == nil {
		var ret string
		return ret
	}
	return *o.ServiceAddress
}

// GetServiceAddressOk returns a tuple with the ServiceAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceAddressOk() (*string, bool) {
	if o == nil || o.ServiceAddress == nil {
		return nil, false
	}
	return o.ServiceAddress, true
}

// HasServiceAddress returns a boolean if a field has been set.
func (o *Service) HasServiceAddress() bool {
	if o != nil && o.ServiceAddress != nil {
		return true
	}

	return false
}

// SetServiceAddress gets a reference to the given string and assigns it to the ServiceAddress field.
func (o *Service) SetServiceAddress(v string) {
	o.ServiceAddress = &v
}

// GetServiceTransport returns the ServiceTransport field value if set, zero value otherwise.
func (o *Service) GetServiceTransport() string {
	if o == nil || o.ServiceTransport == nil {
		var ret string
		return ret
	}
	return *o.ServiceTransport
}

// GetServiceTransportOk returns a tuple with the ServiceTransport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceTransportOk() (*string, bool) {
	if o == nil || o.ServiceTransport == nil {
		return nil, false
	}
	return o.ServiceTransport, true
}

// HasServiceTransport returns a boolean if a field has been set.
func (o *Service) HasServiceTransport() bool {
	if o != nil && o.ServiceTransport != nil {
		return true
	}

	return false
}

// SetServiceTransport gets a reference to the given string and assigns it to the ServiceTransport field.
func (o *Service) SetServiceTransport(v string) {
	o.ServiceTransport = &v
}

// GetServiceVhost returns the ServiceVhost field value if set, zero value otherwise.
func (o *Service) GetServiceVhost() string {
	if o == nil || o.ServiceVhost == nil {
		var ret string
		return ret
	}
	return *o.ServiceVhost
}

// GetServiceVhostOk returns a tuple with the ServiceVhost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceVhostOk() (*string, bool) {
	if o == nil || o.ServiceVhost == nil {
		return nil, false
	}
	return o.ServiceVhost, true
}

// HasServiceVhost returns a boolean if a field has been set.
func (o *Service) HasServiceVhost() bool {
	if o != nil && o.ServiceVhost != nil {
		return true
	}

	return false
}

// SetServiceVhost gets a reference to the given string and assigns it to the ServiceVhost field.
func (o *Service) SetServiceVhost(v string) {
	o.ServiceVhost = &v
}

// GetServicePort returns the ServicePort field value if set, zero value otherwise.
func (o *Service) GetServicePort() string {
	if o == nil || o.ServicePort == nil {
		var ret string
		return ret
	}
	return *o.ServicePort
}

// GetServicePortOk returns a tuple with the ServicePort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServicePortOk() (*string, bool) {
	if o == nil || o.ServicePort == nil {
		return nil, false
	}
	return o.ServicePort, true
}

// HasServicePort returns a boolean if a field has been set.
func (o *Service) HasServicePort() bool {
	if o != nil && o.ServicePort != nil {
		return true
	}

	return false
}

// SetServicePort gets a reference to the given string and assigns it to the ServicePort field.
func (o *Service) SetServicePort(v string) {
	o.ServicePort = &v
}

// GetServiceData returns the ServiceData field value if set, zero value otherwise.
func (o *Service) GetServiceData() map[string]string {
	if o == nil || o.ServiceData == nil {
		var ret map[string]string
		return ret
	}
	return *o.ServiceData
}

// GetServiceDataOk returns a tuple with the ServiceData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceDataOk() (*map[string]string, bool) {
	if o == nil || o.ServiceData == nil {
		return nil, false
	}
	return o.ServiceData, true
}

// HasServiceData returns a boolean if a field has been set.
func (o *Service) HasServiceData() bool {
	if o != nil && o.ServiceData != nil {
		return true
	}

	return false
}

// SetServiceData gets a reference to the given map[string]string and assigns it to the ServiceData field.
func (o *Service) SetServiceData(v map[string]string) {
	o.ServiceData = &v
}

// GetServiceProtocol returns the ServiceProtocol field value if set, zero value otherwise.
func (o *Service) GetServiceProtocol() string {
	if o == nil || o.ServiceProtocol == nil {
		var ret string
		return ret
	}
	return *o.ServiceProtocol
}

// GetServiceProtocolOk returns a tuple with the ServiceProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceProtocolOk() (*string, bool) {
	if o == nil || o.ServiceProtocol == nil {
		return nil, false
	}
	return o.ServiceProtocol, true
}

// HasServiceProtocol returns a boolean if a field has been set.
func (o *Service) HasServiceProtocol() bool {
	if o != nil && o.ServiceProtocol != nil {
		return true
	}

	return false
}

// SetServiceProtocol gets a reference to the given string and assigns it to the ServiceProtocol field.
func (o *Service) SetServiceProtocol(v string) {
	o.ServiceProtocol = &v
}

// GetServiceSummary returns the ServiceSummary field value if set, zero value otherwise.
func (o *Service) GetServiceSummary() string {
	if o == nil || o.ServiceSummary == nil {
		var ret string
		return ret
	}
	return *o.ServiceSummary
}

// GetServiceSummaryOk returns a tuple with the ServiceSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceSummaryOk() (*string, bool) {
	if o == nil || o.ServiceSummary == nil {
		return nil, false
	}
	return o.ServiceSummary, true
}

// HasServiceSummary returns a boolean if a field has been set.
func (o *Service) HasServiceSummary() bool {
	if o != nil && o.ServiceSummary != nil {
		return true
	}

	return false
}

// SetServiceSummary gets a reference to the given string and assigns it to the ServiceSummary field.
func (o *Service) SetServiceSummary(v string) {
	o.ServiceSummary = &v
}

// GetServiceScreenshotLink returns the ServiceScreenshotLink field value if set, zero value otherwise.
func (o *Service) GetServiceScreenshotLink() string {
	if o == nil || o.ServiceScreenshotLink == nil {
		var ret string
		return ret
	}
	return *o.ServiceScreenshotLink
}

// GetServiceScreenshotLinkOk returns a tuple with the ServiceScreenshotLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceScreenshotLinkOk() (*string, bool) {
	if o == nil || o.ServiceScreenshotLink == nil {
		return nil, false
	}
	return o.ServiceScreenshotLink, true
}

// HasServiceScreenshotLink returns a boolean if a field has been set.
func (o *Service) HasServiceScreenshotLink() bool {
	if o != nil && o.ServiceScreenshotLink != nil {
		return true
	}

	return false
}

// SetServiceScreenshotLink gets a reference to the given string and assigns it to the ServiceScreenshotLink field.
func (o *Service) SetServiceScreenshotLink(v string) {
	o.ServiceScreenshotLink = &v
}

// GetServiceLink returns the ServiceLink field value if set, zero value otherwise.
func (o *Service) GetServiceLink() string {
	if o == nil || o.ServiceLink == nil {
		var ret string
		return ret
	}
	return *o.ServiceLink
}

// GetServiceLinkOk returns a tuple with the ServiceLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceLinkOk() (*string, bool) {
	if o == nil || o.ServiceLink == nil {
		return nil, false
	}
	return o.ServiceLink, true
}

// HasServiceLink returns a boolean if a field has been set.
func (o *Service) HasServiceLink() bool {
	if o != nil && o.ServiceLink != nil {
		return true
	}

	return false
}

// SetServiceLink gets a reference to the given string and assigns it to the ServiceLink field.
func (o *Service) SetServiceLink(v string) {
	o.ServiceLink = &v
}

// GetId returns the Id field value
func (o *Service) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Service) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Service) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Service) GetCreatedAt() int64 {
	if o == nil || o.CreatedAt == nil {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetCreatedAtOk() (*int64, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Service) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Service) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Service) GetUpdatedAt() int64 {
	if o == nil || o.UpdatedAt == nil {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Service) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Service) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *Service) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *Service) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *Service) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *Service) GetSiteId() string {
	if o == nil || o.SiteId == nil {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetSiteIdOk() (*string, bool) {
	if o == nil || o.SiteId == nil {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *Service) HasSiteId() bool {
	if o != nil && o.SiteId != nil {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *Service) SetSiteId(v string) {
	o.SiteId = &v
}

// GetAlive returns the Alive field value if set, zero value otherwise.
func (o *Service) GetAlive() bool {
	if o == nil || o.Alive == nil {
		var ret bool
		return ret
	}
	return *o.Alive
}

// GetAliveOk returns a tuple with the Alive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAliveOk() (*bool, bool) {
	if o == nil || o.Alive == nil {
		return nil, false
	}
	return o.Alive, true
}

// HasAlive returns a boolean if a field has been set.
func (o *Service) HasAlive() bool {
	if o != nil && o.Alive != nil {
		return true
	}

	return false
}

// SetAlive gets a reference to the given bool and assigns it to the Alive field.
func (o *Service) SetAlive(v bool) {
	o.Alive = &v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *Service) GetFirstSeen() int64 {
	if o == nil || o.FirstSeen == nil {
		var ret int64
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetFirstSeenOk() (*int64, bool) {
	if o == nil || o.FirstSeen == nil {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *Service) HasFirstSeen() bool {
	if o != nil && o.FirstSeen != nil {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given int64 and assigns it to the FirstSeen field.
func (o *Service) SetFirstSeen(v int64) {
	o.FirstSeen = &v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *Service) GetLastSeen() int64 {
	if o == nil || o.LastSeen == nil {
		var ret int64
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetLastSeenOk() (*int64, bool) {
	if o == nil || o.LastSeen == nil {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *Service) HasLastSeen() bool {
	if o != nil && o.LastSeen != nil {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given int64 and assigns it to the LastSeen field.
func (o *Service) SetLastSeen(v int64) {
	o.LastSeen = &v
}

// GetDetectedBy returns the DetectedBy field value if set, zero value otherwise.
func (o *Service) GetDetectedBy() string {
	if o == nil || o.DetectedBy == nil {
		var ret string
		return ret
	}
	return *o.DetectedBy
}

// GetDetectedByOk returns a tuple with the DetectedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetDetectedByOk() (*string, bool) {
	if o == nil || o.DetectedBy == nil {
		return nil, false
	}
	return o.DetectedBy, true
}

// HasDetectedBy returns a boolean if a field has been set.
func (o *Service) HasDetectedBy() bool {
	if o != nil && o.DetectedBy != nil {
		return true
	}

	return false
}

// SetDetectedBy gets a reference to the given string and assigns it to the DetectedBy field.
func (o *Service) SetDetectedBy(v string) {
	o.DetectedBy = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Service) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Service) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Service) SetType(v string) {
	o.Type = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *Service) GetOs() string {
	if o == nil || o.Os == nil {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetOsOk() (*string, bool) {
	if o == nil || o.Os == nil {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *Service) HasOs() bool {
	if o != nil && o.Os != nil {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *Service) SetOs(v string) {
	o.Os = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *Service) GetOsVersion() string {
	if o == nil || o.OsVersion == nil {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetOsVersionOk() (*string, bool) {
	if o == nil || o.OsVersion == nil {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *Service) HasOsVersion() bool {
	if o != nil && o.OsVersion != nil {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *Service) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetHw returns the Hw field value if set, zero value otherwise.
func (o *Service) GetHw() string {
	if o == nil || o.Hw == nil {
		var ret string
		return ret
	}
	return *o.Hw
}

// GetHwOk returns a tuple with the Hw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetHwOk() (*string, bool) {
	if o == nil || o.Hw == nil {
		return nil, false
	}
	return o.Hw, true
}

// HasHw returns a boolean if a field has been set.
func (o *Service) HasHw() bool {
	if o != nil && o.Hw != nil {
		return true
	}

	return false
}

// SetHw gets a reference to the given string and assigns it to the Hw field.
func (o *Service) SetHw(v string) {
	o.Hw = &v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *Service) GetAddresses() []string {
	if o == nil || o.Addresses == nil {
		var ret []string
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAddressesOk() (*[]string, bool) {
	if o == nil || o.Addresses == nil {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *Service) HasAddresses() bool {
	if o != nil && o.Addresses != nil {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []string and assigns it to the Addresses field.
func (o *Service) SetAddresses(v []string) {
	o.Addresses = &v
}

// GetAddressesExtra returns the AddressesExtra field value if set, zero value otherwise.
func (o *Service) GetAddressesExtra() []string {
	if o == nil || o.AddressesExtra == nil {
		var ret []string
		return ret
	}
	return *o.AddressesExtra
}

// GetAddressesExtraOk returns a tuple with the AddressesExtra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAddressesExtraOk() (*[]string, bool) {
	if o == nil || o.AddressesExtra == nil {
		return nil, false
	}
	return o.AddressesExtra, true
}

// HasAddressesExtra returns a boolean if a field has been set.
func (o *Service) HasAddressesExtra() bool {
	if o != nil && o.AddressesExtra != nil {
		return true
	}

	return false
}

// SetAddressesExtra gets a reference to the given []string and assigns it to the AddressesExtra field.
func (o *Service) SetAddressesExtra(v []string) {
	o.AddressesExtra = &v
}

// GetMacs returns the Macs field value if set, zero value otherwise.
func (o *Service) GetMacs() []string {
	if o == nil || o.Macs == nil {
		var ret []string
		return ret
	}
	return *o.Macs
}

// GetMacsOk returns a tuple with the Macs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetMacsOk() (*[]string, bool) {
	if o == nil || o.Macs == nil {
		return nil, false
	}
	return o.Macs, true
}

// HasMacs returns a boolean if a field has been set.
func (o *Service) HasMacs() bool {
	if o != nil && o.Macs != nil {
		return true
	}

	return false
}

// SetMacs gets a reference to the given []string and assigns it to the Macs field.
func (o *Service) SetMacs(v []string) {
	o.Macs = &v
}

// GetMacVendors returns the MacVendors field value if set, zero value otherwise.
func (o *Service) GetMacVendors() []string {
	if o == nil || o.MacVendors == nil {
		var ret []string
		return ret
	}
	return *o.MacVendors
}

// GetMacVendorsOk returns a tuple with the MacVendors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetMacVendorsOk() (*[]string, bool) {
	if o == nil || o.MacVendors == nil {
		return nil, false
	}
	return o.MacVendors, true
}

// HasMacVendors returns a boolean if a field has been set.
func (o *Service) HasMacVendors() bool {
	if o != nil && o.MacVendors != nil {
		return true
	}

	return false
}

// SetMacVendors gets a reference to the given []string and assigns it to the MacVendors field.
func (o *Service) SetMacVendors(v []string) {
	o.MacVendors = &v
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *Service) GetNames() []string {
	if o == nil || o.Names == nil {
		var ret []string
		return ret
	}
	return *o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetNamesOk() (*[]string, bool) {
	if o == nil || o.Names == nil {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *Service) HasNames() bool {
	if o != nil && o.Names != nil {
		return true
	}

	return false
}

// SetNames gets a reference to the given []string and assigns it to the Names field.
func (o *Service) SetNames(v []string) {
	o.Names = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *Service) GetDomains() []string {
	if o == nil || o.Domains == nil {
		var ret []string
		return ret
	}
	return *o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetDomainsOk() (*[]string, bool) {
	if o == nil || o.Domains == nil {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *Service) HasDomains() bool {
	if o != nil && o.Domains != nil {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *Service) SetDomains(v []string) {
	o.Domains = &v
}

// GetServiceCount returns the ServiceCount field value if set, zero value otherwise.
func (o *Service) GetServiceCount() int64 {
	if o == nil || o.ServiceCount == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCount
}

// GetServiceCountOk returns a tuple with the ServiceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceCountOk() (*int64, bool) {
	if o == nil || o.ServiceCount == nil {
		return nil, false
	}
	return o.ServiceCount, true
}

// HasServiceCount returns a boolean if a field has been set.
func (o *Service) HasServiceCount() bool {
	if o != nil && o.ServiceCount != nil {
		return true
	}

	return false
}

// SetServiceCount gets a reference to the given int64 and assigns it to the ServiceCount field.
func (o *Service) SetServiceCount(v int64) {
	o.ServiceCount = &v
}

// GetServiceCountTcp returns the ServiceCountTcp field value if set, zero value otherwise.
func (o *Service) GetServiceCountTcp() int64 {
	if o == nil || o.ServiceCountTcp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountTcp
}

// GetServiceCountTcpOk returns a tuple with the ServiceCountTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceCountTcpOk() (*int64, bool) {
	if o == nil || o.ServiceCountTcp == nil {
		return nil, false
	}
	return o.ServiceCountTcp, true
}

// HasServiceCountTcp returns a boolean if a field has been set.
func (o *Service) HasServiceCountTcp() bool {
	if o != nil && o.ServiceCountTcp != nil {
		return true
	}

	return false
}

// SetServiceCountTcp gets a reference to the given int64 and assigns it to the ServiceCountTcp field.
func (o *Service) SetServiceCountTcp(v int64) {
	o.ServiceCountTcp = &v
}

// GetServiceCountUdp returns the ServiceCountUdp field value if set, zero value otherwise.
func (o *Service) GetServiceCountUdp() int64 {
	if o == nil || o.ServiceCountUdp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountUdp
}

// GetServiceCountUdpOk returns a tuple with the ServiceCountUdp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceCountUdpOk() (*int64, bool) {
	if o == nil || o.ServiceCountUdp == nil {
		return nil, false
	}
	return o.ServiceCountUdp, true
}

// HasServiceCountUdp returns a boolean if a field has been set.
func (o *Service) HasServiceCountUdp() bool {
	if o != nil && o.ServiceCountUdp != nil {
		return true
	}

	return false
}

// SetServiceCountUdp gets a reference to the given int64 and assigns it to the ServiceCountUdp field.
func (o *Service) SetServiceCountUdp(v int64) {
	o.ServiceCountUdp = &v
}

// GetServiceCountArp returns the ServiceCountArp field value if set, zero value otherwise.
func (o *Service) GetServiceCountArp() int64 {
	if o == nil || o.ServiceCountArp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountArp
}

// GetServiceCountArpOk returns a tuple with the ServiceCountArp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceCountArpOk() (*int64, bool) {
	if o == nil || o.ServiceCountArp == nil {
		return nil, false
	}
	return o.ServiceCountArp, true
}

// HasServiceCountArp returns a boolean if a field has been set.
func (o *Service) HasServiceCountArp() bool {
	if o != nil && o.ServiceCountArp != nil {
		return true
	}

	return false
}

// SetServiceCountArp gets a reference to the given int64 and assigns it to the ServiceCountArp field.
func (o *Service) SetServiceCountArp(v int64) {
	o.ServiceCountArp = &v
}

// GetServiceCountIcmp returns the ServiceCountIcmp field value if set, zero value otherwise.
func (o *Service) GetServiceCountIcmp() int64 {
	if o == nil || o.ServiceCountIcmp == nil {
		var ret int64
		return ret
	}
	return *o.ServiceCountIcmp
}

// GetServiceCountIcmpOk returns a tuple with the ServiceCountIcmp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServiceCountIcmpOk() (*int64, bool) {
	if o == nil || o.ServiceCountIcmp == nil {
		return nil, false
	}
	return o.ServiceCountIcmp, true
}

// HasServiceCountIcmp returns a boolean if a field has been set.
func (o *Service) HasServiceCountIcmp() bool {
	if o != nil && o.ServiceCountIcmp != nil {
		return true
	}

	return false
}

// SetServiceCountIcmp gets a reference to the given int64 and assigns it to the ServiceCountIcmp field.
func (o *Service) SetServiceCountIcmp(v int64) {
	o.ServiceCountIcmp = &v
}

// GetLowestTtl returns the LowestTtl field value if set, zero value otherwise.
func (o *Service) GetLowestTtl() int64 {
	if o == nil || o.LowestTtl == nil {
		var ret int64
		return ret
	}
	return *o.LowestTtl
}

// GetLowestTtlOk returns a tuple with the LowestTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetLowestTtlOk() (*int64, bool) {
	if o == nil || o.LowestTtl == nil {
		return nil, false
	}
	return o.LowestTtl, true
}

// HasLowestTtl returns a boolean if a field has been set.
func (o *Service) HasLowestTtl() bool {
	if o != nil && o.LowestTtl != nil {
		return true
	}

	return false
}

// SetLowestTtl gets a reference to the given int64 and assigns it to the LowestTtl field.
func (o *Service) SetLowestTtl(v int64) {
	o.LowestTtl = &v
}

// GetLowestRtt returns the LowestRtt field value if set, zero value otherwise.
func (o *Service) GetLowestRtt() int64 {
	if o == nil || o.LowestRtt == nil {
		var ret int64
		return ret
	}
	return *o.LowestRtt
}

// GetLowestRttOk returns a tuple with the LowestRtt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetLowestRttOk() (*int64, bool) {
	if o == nil || o.LowestRtt == nil {
		return nil, false
	}
	return o.LowestRtt, true
}

// HasLowestRtt returns a boolean if a field has been set.
func (o *Service) HasLowestRtt() bool {
	if o != nil && o.LowestRtt != nil {
		return true
	}

	return false
}

// SetLowestRtt gets a reference to the given int64 and assigns it to the LowestRtt field.
func (o *Service) SetLowestRtt(v int64) {
	o.LowestRtt = &v
}

// GetLastAgentId returns the LastAgentId field value if set, zero value otherwise.
func (o *Service) GetLastAgentId() string {
	if o == nil || o.LastAgentId == nil {
		var ret string
		return ret
	}
	return *o.LastAgentId
}

// GetLastAgentIdOk returns a tuple with the LastAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetLastAgentIdOk() (*string, bool) {
	if o == nil || o.LastAgentId == nil {
		return nil, false
	}
	return o.LastAgentId, true
}

// HasLastAgentId returns a boolean if a field has been set.
func (o *Service) HasLastAgentId() bool {
	if o != nil && o.LastAgentId != nil {
		return true
	}

	return false
}

// SetLastAgentId gets a reference to the given string and assigns it to the LastAgentId field.
func (o *Service) SetLastAgentId(v string) {
	o.LastAgentId = &v
}

// GetLastTaskId returns the LastTaskId field value if set, zero value otherwise.
func (o *Service) GetLastTaskId() string {
	if o == nil || o.LastTaskId == nil {
		var ret string
		return ret
	}
	return *o.LastTaskId
}

// GetLastTaskIdOk returns a tuple with the LastTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetLastTaskIdOk() (*string, bool) {
	if o == nil || o.LastTaskId == nil {
		return nil, false
	}
	return o.LastTaskId, true
}

// HasLastTaskId returns a boolean if a field has been set.
func (o *Service) HasLastTaskId() bool {
	if o != nil && o.LastTaskId != nil {
		return true
	}

	return false
}

// SetLastTaskId gets a reference to the given string and assigns it to the LastTaskId field.
func (o *Service) SetLastTaskId(v string) {
	o.LastTaskId = &v
}

// GetNewestMac returns the NewestMac field value if set, zero value otherwise.
func (o *Service) GetNewestMac() string {
	if o == nil || o.NewestMac == nil {
		var ret string
		return ret
	}
	return *o.NewestMac
}

// GetNewestMacOk returns a tuple with the NewestMac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetNewestMacOk() (*string, bool) {
	if o == nil || o.NewestMac == nil {
		return nil, false
	}
	return o.NewestMac, true
}

// HasNewestMac returns a boolean if a field has been set.
func (o *Service) HasNewestMac() bool {
	if o != nil && o.NewestMac != nil {
		return true
	}

	return false
}

// SetNewestMac gets a reference to the given string and assigns it to the NewestMac field.
func (o *Service) SetNewestMac(v string) {
	o.NewestMac = &v
}

// GetNewestMacVendor returns the NewestMacVendor field value if set, zero value otherwise.
func (o *Service) GetNewestMacVendor() string {
	if o == nil || o.NewestMacVendor == nil {
		var ret string
		return ret
	}
	return *o.NewestMacVendor
}

// GetNewestMacVendorOk returns a tuple with the NewestMacVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetNewestMacVendorOk() (*string, bool) {
	if o == nil || o.NewestMacVendor == nil {
		return nil, false
	}
	return o.NewestMacVendor, true
}

// HasNewestMacVendor returns a boolean if a field has been set.
func (o *Service) HasNewestMacVendor() bool {
	if o != nil && o.NewestMacVendor != nil {
		return true
	}

	return false
}

// SetNewestMacVendor gets a reference to the given string and assigns it to the NewestMacVendor field.
func (o *Service) SetNewestMacVendor(v string) {
	o.NewestMacVendor = &v
}

// GetNewestMacAge returns the NewestMacAge field value if set, zero value otherwise.
func (o *Service) GetNewestMacAge() int64 {
	if o == nil || o.NewestMacAge == nil {
		var ret int64
		return ret
	}
	return *o.NewestMacAge
}

// GetNewestMacAgeOk returns a tuple with the NewestMacAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetNewestMacAgeOk() (*int64, bool) {
	if o == nil || o.NewestMacAge == nil {
		return nil, false
	}
	return o.NewestMacAge, true
}

// HasNewestMacAge returns a boolean if a field has been set.
func (o *Service) HasNewestMacAge() bool {
	if o != nil && o.NewestMacAge != nil {
		return true
	}

	return false
}

// SetNewestMacAge gets a reference to the given int64 and assigns it to the NewestMacAge field.
func (o *Service) SetNewestMacAge(v int64) {
	o.NewestMacAge = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *Service) GetComments() string {
	if o == nil || o.Comments == nil {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetCommentsOk() (*string, bool) {
	if o == nil || o.Comments == nil {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *Service) HasComments() bool {
	if o != nil && o.Comments != nil {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *Service) SetComments(v string) {
	o.Comments = &v
}

// GetServicePortsTcp returns the ServicePortsTcp field value if set, zero value otherwise.
func (o *Service) GetServicePortsTcp() []string {
	if o == nil || o.ServicePortsTcp == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsTcp
}

// GetServicePortsTcpOk returns a tuple with the ServicePortsTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServicePortsTcpOk() (*[]string, bool) {
	if o == nil || o.ServicePortsTcp == nil {
		return nil, false
	}
	return o.ServicePortsTcp, true
}

// HasServicePortsTcp returns a boolean if a field has been set.
func (o *Service) HasServicePortsTcp() bool {
	if o != nil && o.ServicePortsTcp != nil {
		return true
	}

	return false
}

// SetServicePortsTcp gets a reference to the given []string and assigns it to the ServicePortsTcp field.
func (o *Service) SetServicePortsTcp(v []string) {
	o.ServicePortsTcp = &v
}

// GetServicePortsUdp returns the ServicePortsUdp field value if set, zero value otherwise.
func (o *Service) GetServicePortsUdp() []string {
	if o == nil || o.ServicePortsUdp == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsUdp
}

// GetServicePortsUdpOk returns a tuple with the ServicePortsUdp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServicePortsUdpOk() (*[]string, bool) {
	if o == nil || o.ServicePortsUdp == nil {
		return nil, false
	}
	return o.ServicePortsUdp, true
}

// HasServicePortsUdp returns a boolean if a field has been set.
func (o *Service) HasServicePortsUdp() bool {
	if o != nil && o.ServicePortsUdp != nil {
		return true
	}

	return false
}

// SetServicePortsUdp gets a reference to the given []string and assigns it to the ServicePortsUdp field.
func (o *Service) SetServicePortsUdp(v []string) {
	o.ServicePortsUdp = &v
}

// GetServicePortsProtocols returns the ServicePortsProtocols field value if set, zero value otherwise.
func (o *Service) GetServicePortsProtocols() []string {
	if o == nil || o.ServicePortsProtocols == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsProtocols
}

// GetServicePortsProtocolsOk returns a tuple with the ServicePortsProtocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServicePortsProtocolsOk() (*[]string, bool) {
	if o == nil || o.ServicePortsProtocols == nil {
		return nil, false
	}
	return o.ServicePortsProtocols, true
}

// HasServicePortsProtocols returns a boolean if a field has been set.
func (o *Service) HasServicePortsProtocols() bool {
	if o != nil && o.ServicePortsProtocols != nil {
		return true
	}

	return false
}

// SetServicePortsProtocols gets a reference to the given []string and assigns it to the ServicePortsProtocols field.
func (o *Service) SetServicePortsProtocols(v []string) {
	o.ServicePortsProtocols = &v
}

// GetServicePortsProducts returns the ServicePortsProducts field value if set, zero value otherwise.
func (o *Service) GetServicePortsProducts() []string {
	if o == nil || o.ServicePortsProducts == nil {
		var ret []string
		return ret
	}
	return *o.ServicePortsProducts
}

// GetServicePortsProductsOk returns a tuple with the ServicePortsProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServicePortsProductsOk() (*[]string, bool) {
	if o == nil || o.ServicePortsProducts == nil {
		return nil, false
	}
	return o.ServicePortsProducts, true
}

// HasServicePortsProducts returns a boolean if a field has been set.
func (o *Service) HasServicePortsProducts() bool {
	if o != nil && o.ServicePortsProducts != nil {
		return true
	}

	return false
}

// SetServicePortsProducts gets a reference to the given []string and assigns it to the ServicePortsProducts field.
func (o *Service) SetServicePortsProducts(v []string) {
	o.ServicePortsProducts = &v
}

// GetOrgName returns the OrgName field value if set, zero value otherwise.
func (o *Service) GetOrgName() string {
	if o == nil || o.OrgName == nil {
		var ret string
		return ret
	}
	return *o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetOrgNameOk() (*string, bool) {
	if o == nil || o.OrgName == nil {
		return nil, false
	}
	return o.OrgName, true
}

// HasOrgName returns a boolean if a field has been set.
func (o *Service) HasOrgName() bool {
	if o != nil && o.OrgName != nil {
		return true
	}

	return false
}

// SetOrgName gets a reference to the given string and assigns it to the OrgName field.
func (o *Service) SetOrgName(v string) {
	o.OrgName = &v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *Service) GetSiteName() string {
	if o == nil || o.SiteName == nil {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetSiteNameOk() (*string, bool) {
	if o == nil || o.SiteName == nil {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *Service) HasSiteName() bool {
	if o != nil && o.SiteName != nil {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *Service) SetSiteName(v string) {
	o.SiteName = &v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *Service) GetAgentName() string {
	if o == nil || o.AgentName == nil {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAgentNameOk() (*string, bool) {
	if o == nil || o.AgentName == nil {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *Service) HasAgentName() bool {
	if o != nil && o.AgentName != nil {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *Service) SetAgentName(v string) {
	o.AgentName = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Service) GetTags() map[string]string {
	if o == nil || o.Tags == nil {
		var ret map[string]string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetTagsOk() (*map[string]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Service) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]string and assigns it to the Tags field.
func (o *Service) SetTags(v map[string]string) {
	o.Tags = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *Service) GetServices() map[string]map[string]string {
	if o == nil || o.Services == nil {
		var ret map[string]map[string]string
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetServicesOk() (*map[string]map[string]string, bool) {
	if o == nil || o.Services == nil {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *Service) HasServices() bool {
	if o != nil && o.Services != nil {
		return true
	}

	return false
}

// SetServices gets a reference to the given map[string]map[string]string and assigns it to the Services field.
func (o *Service) SetServices(v map[string]map[string]string) {
	o.Services = &v
}

// GetRtts returns the Rtts field value if set, zero value otherwise.
func (o *Service) GetRtts() map[string]map[string]interface{} {
	if o == nil || o.Rtts == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.Rtts
}

// GetRttsOk returns a tuple with the Rtts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetRttsOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || o.Rtts == nil {
		return nil, false
	}
	return o.Rtts, true
}

// HasRtts returns a boolean if a field has been set.
func (o *Service) HasRtts() bool {
	if o != nil && o.Rtts != nil {
		return true
	}

	return false
}

// SetRtts gets a reference to the given map[string]map[string]interface{} and assigns it to the Rtts field.
func (o *Service) SetRtts(v map[string]map[string]interface{}) {
	o.Rtts = &v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *Service) GetCredentials() map[string]map[string]bool {
	if o == nil || o.Credentials == nil {
		var ret map[string]map[string]bool
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetCredentialsOk() (*map[string]map[string]bool, bool) {
	if o == nil || o.Credentials == nil {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *Service) HasCredentials() bool {
	if o != nil && o.Credentials != nil {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given map[string]map[string]bool and assigns it to the Credentials field.
func (o *Service) SetCredentials(v map[string]map[string]bool) {
	o.Credentials = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Service) GetAttributes() map[string]string {
	if o == nil || o.Attributes == nil {
		var ret map[string]string
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAttributesOk() (*map[string]string, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Service) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]string and assigns it to the Attributes field.
func (o *Service) SetAttributes(v map[string]string) {
	o.Attributes = &v
}

func (o Service) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_id"] = o.ServiceId
	}
	if o.ServiceAssetId != nil {
		toSerialize["service_asset_id"] = o.ServiceAssetId
	}
	if o.ServiceCreatedAt != nil {
		toSerialize["service_created_at"] = o.ServiceCreatedAt
	}
	if o.ServiceUpdatedAt != nil {
		toSerialize["service_updated_at"] = o.ServiceUpdatedAt
	}
	if o.ServiceAddress != nil {
		toSerialize["service_address"] = o.ServiceAddress
	}
	if o.ServiceTransport != nil {
		toSerialize["service_transport"] = o.ServiceTransport
	}
	if o.ServiceVhost != nil {
		toSerialize["service_vhost"] = o.ServiceVhost
	}
	if o.ServicePort != nil {
		toSerialize["service_port"] = o.ServicePort
	}
	if o.ServiceData != nil {
		toSerialize["service_data"] = o.ServiceData
	}
	if o.ServiceProtocol != nil {
		toSerialize["service_protocol"] = o.ServiceProtocol
	}
	if o.ServiceSummary != nil {
		toSerialize["service_summary"] = o.ServiceSummary
	}
	if o.ServiceScreenshotLink != nil {
		toSerialize["service_screenshot_link"] = o.ServiceScreenshotLink
	}
	if o.ServiceLink != nil {
		toSerialize["service_link"] = o.ServiceLink
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.OrganizationId != nil {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if o.SiteId != nil {
		toSerialize["site_id"] = o.SiteId
	}
	if o.Alive != nil {
		toSerialize["alive"] = o.Alive
	}
	if o.FirstSeen != nil {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if o.LastSeen != nil {
		toSerialize["last_seen"] = o.LastSeen
	}
	if o.DetectedBy != nil {
		toSerialize["detected_by"] = o.DetectedBy
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Os != nil {
		toSerialize["os"] = o.Os
	}
	if o.OsVersion != nil {
		toSerialize["os_version"] = o.OsVersion
	}
	if o.Hw != nil {
		toSerialize["hw"] = o.Hw
	}
	if o.Addresses != nil {
		toSerialize["addresses"] = o.Addresses
	}
	if o.AddressesExtra != nil {
		toSerialize["addresses_extra"] = o.AddressesExtra
	}
	if o.Macs != nil {
		toSerialize["macs"] = o.Macs
	}
	if o.MacVendors != nil {
		toSerialize["mac_vendors"] = o.MacVendors
	}
	if o.Names != nil {
		toSerialize["names"] = o.Names
	}
	if o.Domains != nil {
		toSerialize["domains"] = o.Domains
	}
	if o.ServiceCount != nil {
		toSerialize["service_count"] = o.ServiceCount
	}
	if o.ServiceCountTcp != nil {
		toSerialize["service_count_tcp"] = o.ServiceCountTcp
	}
	if o.ServiceCountUdp != nil {
		toSerialize["service_count_udp"] = o.ServiceCountUdp
	}
	if o.ServiceCountArp != nil {
		toSerialize["service_count_arp"] = o.ServiceCountArp
	}
	if o.ServiceCountIcmp != nil {
		toSerialize["service_count_icmp"] = o.ServiceCountIcmp
	}
	if o.LowestTtl != nil {
		toSerialize["lowest_ttl"] = o.LowestTtl
	}
	if o.LowestRtt != nil {
		toSerialize["lowest_rtt"] = o.LowestRtt
	}
	if o.LastAgentId != nil {
		toSerialize["last_agent_id"] = o.LastAgentId
	}
	if o.LastTaskId != nil {
		toSerialize["last_task_id"] = o.LastTaskId
	}
	if o.NewestMac != nil {
		toSerialize["newest_mac"] = o.NewestMac
	}
	if o.NewestMacVendor != nil {
		toSerialize["newest_mac_vendor"] = o.NewestMacVendor
	}
	if o.NewestMacAge != nil {
		toSerialize["newest_mac_age"] = o.NewestMacAge
	}
	if o.Comments != nil {
		toSerialize["comments"] = o.Comments
	}
	if o.ServicePortsTcp != nil {
		toSerialize["service_ports_tcp"] = o.ServicePortsTcp
	}
	if o.ServicePortsUdp != nil {
		toSerialize["service_ports_udp"] = o.ServicePortsUdp
	}
	if o.ServicePortsProtocols != nil {
		toSerialize["service_ports_protocols"] = o.ServicePortsProtocols
	}
	if o.ServicePortsProducts != nil {
		toSerialize["service_ports_products"] = o.ServicePortsProducts
	}
	if o.OrgName != nil {
		toSerialize["org_name"] = o.OrgName
	}
	if o.SiteName != nil {
		toSerialize["site_name"] = o.SiteName
	}
	if o.AgentName != nil {
		toSerialize["agent_name"] = o.AgentName
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	if o.Rtts != nil {
		toSerialize["rtts"] = o.Rtts
	}
	if o.Credentials != nil {
		toSerialize["credentials"] = o.Credentials
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableService struct {
	value *Service
	isSet bool
}

func (v NullableService) Get() *Service {
	return v.value
}

func (v *NullableService) Set(val *Service) {
	v.value = val
	v.isSet = true
}

func (v NullableService) IsSet() bool {
	return v.isSet
}

func (v *NullableService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableService(val *Service) *NullableService {
	return &NullableService{value: val, isSet: true}
}

func (v NullableService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
