/*
 * Rumble API
 *
 * Rumble Network Discovery API
 *
 * API version: 1.0.4
 * Contact: support@rumble.run
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
)

// URL A URL to a resource
type URL struct {
	Id *string `json:"id,omitempty"`
}

// NewURL instantiates a new URL object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewURL() *URL {
	this := URL{}
	return &this
}

// NewURLWithDefaults instantiates a new URL object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewURLWithDefaults() *URL {
	this := URL{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *URL) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URL) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *URL) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *URL) SetId(v string) {
	o.Id = &v
}

func (o URL) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableURL struct {
	value *URL
	isSet bool
}

func (v NullableURL) Get() *URL {
	return v.value
}

func (v *NullableURL) Set(val *URL) {
	v.value = val
	v.isSet = true
}

func (v NullableURL) IsSet() bool {
	return v.isSet
}

func (v *NullableURL) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableURL(val *URL) *NullableURL {
	return &NullableURL{value: val, isSet: true}
}

func (v NullableURL) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableURL) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
