/*
 * Rumble API
 *
 * Rumble Network Discovery API
 *
 * API version: 1.0.4
 * Contact: support@rumble.run
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
)

// Wireless struct for Wireless
type Wireless struct {
	Id string `json:"id"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	LastSeen *int64 `json:"last_seen,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	SiteId *string `json:"site_id,omitempty"`
	LastAgentId *string `json:"last_agent_id,omitempty"`
	LastTaskId *string `json:"last_task_id,omitempty"`
	Essid *string `json:"essid,omitempty"`
	Bssid *string `json:"bssid,omitempty"`
	Type *string `json:"type,omitempty"`
	Authentication *string `json:"authentication,omitempty"`
	Encryption *string `json:"encryption,omitempty"`
	Signal *int32 `json:"signal,omitempty"`
	Channels *string `json:"channels,omitempty"`
	Interface *string `json:"interface,omitempty"`
	Vendor *string `json:"vendor,omitempty"`
	Family *string `json:"family,omitempty"`
	Data *map[string]string `json:"data,omitempty"`
	OrgName *string `json:"org_name,omitempty"`
	SiteName *string `json:"site_name,omitempty"`
	AgentName *string `json:"agent_name,omitempty"`
}

// NewWireless instantiates a new Wireless object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWireless(id string, ) *Wireless {
	this := Wireless{}
	this.Id = id
	return &this
}

// NewWirelessWithDefaults instantiates a new Wireless object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWirelessWithDefaults() *Wireless {
	this := Wireless{}
	return &this
}

// GetId returns the Id field value
func (o *Wireless) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Wireless) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Wireless) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Wireless) GetCreatedAt() int64 {
	if o == nil || o.CreatedAt == nil {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetCreatedAtOk() (*int64, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Wireless) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Wireless) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *Wireless) GetLastSeen() int64 {
	if o == nil || o.LastSeen == nil {
		var ret int64
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetLastSeenOk() (*int64, bool) {
	if o == nil || o.LastSeen == nil {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *Wireless) HasLastSeen() bool {
	if o != nil && o.LastSeen != nil {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given int64 and assigns it to the LastSeen field.
func (o *Wireless) SetLastSeen(v int64) {
	o.LastSeen = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *Wireless) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *Wireless) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *Wireless) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *Wireless) GetSiteId() string {
	if o == nil || o.SiteId == nil {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetSiteIdOk() (*string, bool) {
	if o == nil || o.SiteId == nil {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *Wireless) HasSiteId() bool {
	if o != nil && o.SiteId != nil {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *Wireless) SetSiteId(v string) {
	o.SiteId = &v
}

// GetLastAgentId returns the LastAgentId field value if set, zero value otherwise.
func (o *Wireless) GetLastAgentId() string {
	if o == nil || o.LastAgentId == nil {
		var ret string
		return ret
	}
	return *o.LastAgentId
}

// GetLastAgentIdOk returns a tuple with the LastAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetLastAgentIdOk() (*string, bool) {
	if o == nil || o.LastAgentId == nil {
		return nil, false
	}
	return o.LastAgentId, true
}

// HasLastAgentId returns a boolean if a field has been set.
func (o *Wireless) HasLastAgentId() bool {
	if o != nil && o.LastAgentId != nil {
		return true
	}

	return false
}

// SetLastAgentId gets a reference to the given string and assigns it to the LastAgentId field.
func (o *Wireless) SetLastAgentId(v string) {
	o.LastAgentId = &v
}

// GetLastTaskId returns the LastTaskId field value if set, zero value otherwise.
func (o *Wireless) GetLastTaskId() string {
	if o == nil || o.LastTaskId == nil {
		var ret string
		return ret
	}
	return *o.LastTaskId
}

// GetLastTaskIdOk returns a tuple with the LastTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetLastTaskIdOk() (*string, bool) {
	if o == nil || o.LastTaskId == nil {
		return nil, false
	}
	return o.LastTaskId, true
}

// HasLastTaskId returns a boolean if a field has been set.
func (o *Wireless) HasLastTaskId() bool {
	if o != nil && o.LastTaskId != nil {
		return true
	}

	return false
}

// SetLastTaskId gets a reference to the given string and assigns it to the LastTaskId field.
func (o *Wireless) SetLastTaskId(v string) {
	o.LastTaskId = &v
}

// GetEssid returns the Essid field value if set, zero value otherwise.
func (o *Wireless) GetEssid() string {
	if o == nil || o.Essid == nil {
		var ret string
		return ret
	}
	return *o.Essid
}

// GetEssidOk returns a tuple with the Essid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetEssidOk() (*string, bool) {
	if o == nil || o.Essid == nil {
		return nil, false
	}
	return o.Essid, true
}

// HasEssid returns a boolean if a field has been set.
func (o *Wireless) HasEssid() bool {
	if o != nil && o.Essid != nil {
		return true
	}

	return false
}

// SetEssid gets a reference to the given string and assigns it to the Essid field.
func (o *Wireless) SetEssid(v string) {
	o.Essid = &v
}

// GetBssid returns the Bssid field value if set, zero value otherwise.
func (o *Wireless) GetBssid() string {
	if o == nil || o.Bssid == nil {
		var ret string
		return ret
	}
	return *o.Bssid
}

// GetBssidOk returns a tuple with the Bssid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetBssidOk() (*string, bool) {
	if o == nil || o.Bssid == nil {
		return nil, false
	}
	return o.Bssid, true
}

// HasBssid returns a boolean if a field has been set.
func (o *Wireless) HasBssid() bool {
	if o != nil && o.Bssid != nil {
		return true
	}

	return false
}

// SetBssid gets a reference to the given string and assigns it to the Bssid field.
func (o *Wireless) SetBssid(v string) {
	o.Bssid = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Wireless) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Wireless) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Wireless) SetType(v string) {
	o.Type = &v
}

// GetAuthentication returns the Authentication field value if set, zero value otherwise.
func (o *Wireless) GetAuthentication() string {
	if o == nil || o.Authentication == nil {
		var ret string
		return ret
	}
	return *o.Authentication
}

// GetAuthenticationOk returns a tuple with the Authentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetAuthenticationOk() (*string, bool) {
	if o == nil || o.Authentication == nil {
		return nil, false
	}
	return o.Authentication, true
}

// HasAuthentication returns a boolean if a field has been set.
func (o *Wireless) HasAuthentication() bool {
	if o != nil && o.Authentication != nil {
		return true
	}

	return false
}

// SetAuthentication gets a reference to the given string and assigns it to the Authentication field.
func (o *Wireless) SetAuthentication(v string) {
	o.Authentication = &v
}

// GetEncryption returns the Encryption field value if set, zero value otherwise.
func (o *Wireless) GetEncryption() string {
	if o == nil || o.Encryption == nil {
		var ret string
		return ret
	}
	return *o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetEncryptionOk() (*string, bool) {
	if o == nil || o.Encryption == nil {
		return nil, false
	}
	return o.Encryption, true
}

// HasEncryption returns a boolean if a field has been set.
func (o *Wireless) HasEncryption() bool {
	if o != nil && o.Encryption != nil {
		return true
	}

	return false
}

// SetEncryption gets a reference to the given string and assigns it to the Encryption field.
func (o *Wireless) SetEncryption(v string) {
	o.Encryption = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *Wireless) GetSignal() int32 {
	if o == nil || o.Signal == nil {
		var ret int32
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetSignalOk() (*int32, bool) {
	if o == nil || o.Signal == nil {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *Wireless) HasSignal() bool {
	if o != nil && o.Signal != nil {
		return true
	}

	return false
}

// SetSignal gets a reference to the given int32 and assigns it to the Signal field.
func (o *Wireless) SetSignal(v int32) {
	o.Signal = &v
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *Wireless) GetChannels() string {
	if o == nil || o.Channels == nil {
		var ret string
		return ret
	}
	return *o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetChannelsOk() (*string, bool) {
	if o == nil || o.Channels == nil {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *Wireless) HasChannels() bool {
	if o != nil && o.Channels != nil {
		return true
	}

	return false
}

// SetChannels gets a reference to the given string and assigns it to the Channels field.
func (o *Wireless) SetChannels(v string) {
	o.Channels = &v
}

// GetInterface returns the Interface field value if set, zero value otherwise.
func (o *Wireless) GetInterface() string {
	if o == nil || o.Interface == nil {
		var ret string
		return ret
	}
	return *o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetInterfaceOk() (*string, bool) {
	if o == nil || o.Interface == nil {
		return nil, false
	}
	return o.Interface, true
}

// HasInterface returns a boolean if a field has been set.
func (o *Wireless) HasInterface() bool {
	if o != nil && o.Interface != nil {
		return true
	}

	return false
}

// SetInterface gets a reference to the given string and assigns it to the Interface field.
func (o *Wireless) SetInterface(v string) {
	o.Interface = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *Wireless) GetVendor() string {
	if o == nil || o.Vendor == nil {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetVendorOk() (*string, bool) {
	if o == nil || o.Vendor == nil {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *Wireless) HasVendor() bool {
	if o != nil && o.Vendor != nil {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *Wireless) SetVendor(v string) {
	o.Vendor = &v
}

// GetFamily returns the Family field value if set, zero value otherwise.
func (o *Wireless) GetFamily() string {
	if o == nil || o.Family == nil {
		var ret string
		return ret
	}
	return *o.Family
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetFamilyOk() (*string, bool) {
	if o == nil || o.Family == nil {
		return nil, false
	}
	return o.Family, true
}

// HasFamily returns a boolean if a field has been set.
func (o *Wireless) HasFamily() bool {
	if o != nil && o.Family != nil {
		return true
	}

	return false
}

// SetFamily gets a reference to the given string and assigns it to the Family field.
func (o *Wireless) SetFamily(v string) {
	o.Family = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Wireless) GetData() map[string]string {
	if o == nil || o.Data == nil {
		var ret map[string]string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetDataOk() (*map[string]string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Wireless) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]string and assigns it to the Data field.
func (o *Wireless) SetData(v map[string]string) {
	o.Data = &v
}

// GetOrgName returns the OrgName field value if set, zero value otherwise.
func (o *Wireless) GetOrgName() string {
	if o == nil || o.OrgName == nil {
		var ret string
		return ret
	}
	return *o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetOrgNameOk() (*string, bool) {
	if o == nil || o.OrgName == nil {
		return nil, false
	}
	return o.OrgName, true
}

// HasOrgName returns a boolean if a field has been set.
func (o *Wireless) HasOrgName() bool {
	if o != nil && o.OrgName != nil {
		return true
	}

	return false
}

// SetOrgName gets a reference to the given string and assigns it to the OrgName field.
func (o *Wireless) SetOrgName(v string) {
	o.OrgName = &v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *Wireless) GetSiteName() string {
	if o == nil || o.SiteName == nil {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetSiteNameOk() (*string, bool) {
	if o == nil || o.SiteName == nil {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *Wireless) HasSiteName() bool {
	if o != nil && o.SiteName != nil {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *Wireless) SetSiteName(v string) {
	o.SiteName = &v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *Wireless) GetAgentName() string {
	if o == nil || o.AgentName == nil {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wireless) GetAgentNameOk() (*string, bool) {
	if o == nil || o.AgentName == nil {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *Wireless) HasAgentName() bool {
	if o != nil && o.AgentName != nil {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *Wireless) SetAgentName(v string) {
	o.AgentName = &v
}

func (o Wireless) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.LastSeen != nil {
		toSerialize["last_seen"] = o.LastSeen
	}
	if o.OrganizationId != nil {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if o.SiteId != nil {
		toSerialize["site_id"] = o.SiteId
	}
	if o.LastAgentId != nil {
		toSerialize["last_agent_id"] = o.LastAgentId
	}
	if o.LastTaskId != nil {
		toSerialize["last_task_id"] = o.LastTaskId
	}
	if o.Essid != nil {
		toSerialize["essid"] = o.Essid
	}
	if o.Bssid != nil {
		toSerialize["bssid"] = o.Bssid
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Authentication != nil {
		toSerialize["authentication"] = o.Authentication
	}
	if o.Encryption != nil {
		toSerialize["encryption"] = o.Encryption
	}
	if o.Signal != nil {
		toSerialize["signal"] = o.Signal
	}
	if o.Channels != nil {
		toSerialize["channels"] = o.Channels
	}
	if o.Interface != nil {
		toSerialize["interface"] = o.Interface
	}
	if o.Vendor != nil {
		toSerialize["vendor"] = o.Vendor
	}
	if o.Family != nil {
		toSerialize["family"] = o.Family
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.OrgName != nil {
		toSerialize["org_name"] = o.OrgName
	}
	if o.SiteName != nil {
		toSerialize["site_name"] = o.SiteName
	}
	if o.AgentName != nil {
		toSerialize["agent_name"] = o.AgentName
	}
	return json.Marshal(toSerialize)
}

type NullableWireless struct {
	value *Wireless
	isSet bool
}

func (v NullableWireless) Get() *Wireless {
	return v.value
}

func (v *NullableWireless) Set(val *Wireless) {
	v.value = val
	v.isSet = true
}

func (v NullableWireless) IsSet() bool {
	return v.isSet
}

func (v *NullableWireless) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWireless(val *Wireless) *NullableWireless {
	return &NullableWireless{value: val, isSet: true}
}

func (v NullableWireless) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWireless) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
