/*
 * Rumble API
 *
 * Rumble Network Discovery API
 *
 * API version: 1.0.0
 * Contact: support@rumble.run
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"bytes"
	"encoding/json"
)

// Organization struct for Organization
type Organization struct {
	Id                     string   `json:"id"`
	CreatedAt              *float32 `json:"created_at,omitempty"`
	UpdatedAt              *float32 `json:"updated_at,omitempty"`
	ClientId               *string  `json:"client_id,omitempty"`
	DownloadToken          *string  `json:"download_token,omitempty"`
	DownloadTokenCreatedAt *float32 `json:"download_token_created_at,omitempty"`
	Permanent              *bool    `json:"permanent,omitempty"`
	Name                   string   `json:"name"`
	Description            *string  `json:"description,omitempty"`
	Inactive               *bool    `json:"inactive,omitempty"`
	DeactivatedAt          *float32 `json:"deactivated_at,omitempty"`
	ServiceCount           *float32 `json:"service_count,omitempty"`
	ServiceCountTcp        *float32 `json:"service_count_tcp,omitempty"`
	ServiceCountUdp        *float32 `json:"service_count_udp,omitempty"`
	ServiceCountArp        *float32 `json:"service_count_arp,omitempty"`
	ServiceCountIcmp       *float32 `json:"service_count_icmp,omitempty"`
	AssetCount             *float32 `json:"asset_count,omitempty"`
	ExportToken            *string  `json:"export_token,omitempty"`
	ExportTokenCreatedAt   *float32 `json:"export_token_created_at,omitempty"`
	ExportTokenLastUsedAt  *float32 `json:"export_token_last_used_at,omitempty"`
	ExportTokenLastUsedBy  *string  `json:"export_token_last_used_by,omitempty"`
	ExportTokenCounter     *float32 `json:"export_token_counter,omitempty"`
}

// GetId returns the Id field value
func (o *Organization) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// SetId sets field value
func (o *Organization) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Organization) GetCreatedAt() float32 {
	if o == nil || o.CreatedAt == nil {
		var ret float32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetCreatedAtOk() (float32, bool) {
	if o == nil || o.CreatedAt == nil {
		var ret float32
		return ret, false
	}
	return *o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Organization) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given float32 and assigns it to the CreatedAt field.
func (o *Organization) SetCreatedAt(v float32) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Organization) GetUpdatedAt() float32 {
	if o == nil || o.UpdatedAt == nil {
		var ret float32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetUpdatedAtOk() (float32, bool) {
	if o == nil || o.UpdatedAt == nil {
		var ret float32
		return ret, false
	}
	return *o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Organization) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given float32 and assigns it to the UpdatedAt field.
func (o *Organization) SetUpdatedAt(v float32) {
	o.UpdatedAt = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *Organization) GetClientId() string {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetClientIdOk() (string, bool) {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret, false
	}
	return *o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *Organization) HasClientId() bool {
	if o != nil && o.ClientId != nil {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *Organization) SetClientId(v string) {
	o.ClientId = &v
}

// GetDownloadToken returns the DownloadToken field value if set, zero value otherwise.
func (o *Organization) GetDownloadToken() string {
	if o == nil || o.DownloadToken == nil {
		var ret string
		return ret
	}
	return *o.DownloadToken
}

// GetDownloadTokenOk returns a tuple with the DownloadToken field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetDownloadTokenOk() (string, bool) {
	if o == nil || o.DownloadToken == nil {
		var ret string
		return ret, false
	}
	return *o.DownloadToken, true
}

// HasDownloadToken returns a boolean if a field has been set.
func (o *Organization) HasDownloadToken() bool {
	if o != nil && o.DownloadToken != nil {
		return true
	}

	return false
}

// SetDownloadToken gets a reference to the given string and assigns it to the DownloadToken field.
func (o *Organization) SetDownloadToken(v string) {
	o.DownloadToken = &v
}

// GetDownloadTokenCreatedAt returns the DownloadTokenCreatedAt field value if set, zero value otherwise.
func (o *Organization) GetDownloadTokenCreatedAt() float32 {
	if o == nil || o.DownloadTokenCreatedAt == nil {
		var ret float32
		return ret
	}
	return *o.DownloadTokenCreatedAt
}

// GetDownloadTokenCreatedAtOk returns a tuple with the DownloadTokenCreatedAt field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetDownloadTokenCreatedAtOk() (float32, bool) {
	if o == nil || o.DownloadTokenCreatedAt == nil {
		var ret float32
		return ret, false
	}
	return *o.DownloadTokenCreatedAt, true
}

// HasDownloadTokenCreatedAt returns a boolean if a field has been set.
func (o *Organization) HasDownloadTokenCreatedAt() bool {
	if o != nil && o.DownloadTokenCreatedAt != nil {
		return true
	}

	return false
}

// SetDownloadTokenCreatedAt gets a reference to the given float32 and assigns it to the DownloadTokenCreatedAt field.
func (o *Organization) SetDownloadTokenCreatedAt(v float32) {
	o.DownloadTokenCreatedAt = &v
}

// GetPermanent returns the Permanent field value if set, zero value otherwise.
func (o *Organization) GetPermanent() bool {
	if o == nil || o.Permanent == nil {
		var ret bool
		return ret
	}
	return *o.Permanent
}

// GetPermanentOk returns a tuple with the Permanent field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetPermanentOk() (bool, bool) {
	if o == nil || o.Permanent == nil {
		var ret bool
		return ret, false
	}
	return *o.Permanent, true
}

// HasPermanent returns a boolean if a field has been set.
func (o *Organization) HasPermanent() bool {
	if o != nil && o.Permanent != nil {
		return true
	}

	return false
}

// SetPermanent gets a reference to the given bool and assigns it to the Permanent field.
func (o *Organization) SetPermanent(v bool) {
	o.Permanent = &v
}

// GetName returns the Name field value
func (o *Organization) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// SetName sets field value
func (o *Organization) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Organization) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetDescriptionOk() (string, bool) {
	if o == nil || o.Description == nil {
		var ret string
		return ret, false
	}
	return *o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Organization) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Organization) SetDescription(v string) {
	o.Description = &v
}

// GetInactive returns the Inactive field value if set, zero value otherwise.
func (o *Organization) GetInactive() bool {
	if o == nil || o.Inactive == nil {
		var ret bool
		return ret
	}
	return *o.Inactive
}

// GetInactiveOk returns a tuple with the Inactive field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetInactiveOk() (bool, bool) {
	if o == nil || o.Inactive == nil {
		var ret bool
		return ret, false
	}
	return *o.Inactive, true
}

// HasInactive returns a boolean if a field has been set.
func (o *Organization) HasInactive() bool {
	if o != nil && o.Inactive != nil {
		return true
	}

	return false
}

// SetInactive gets a reference to the given bool and assigns it to the Inactive field.
func (o *Organization) SetInactive(v bool) {
	o.Inactive = &v
}

// GetDeactivatedAt returns the DeactivatedAt field value if set, zero value otherwise.
func (o *Organization) GetDeactivatedAt() float32 {
	if o == nil || o.DeactivatedAt == nil {
		var ret float32
		return ret
	}
	return *o.DeactivatedAt
}

// GetDeactivatedAtOk returns a tuple with the DeactivatedAt field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetDeactivatedAtOk() (float32, bool) {
	if o == nil || o.DeactivatedAt == nil {
		var ret float32
		return ret, false
	}
	return *o.DeactivatedAt, true
}

// HasDeactivatedAt returns a boolean if a field has been set.
func (o *Organization) HasDeactivatedAt() bool {
	if o != nil && o.DeactivatedAt != nil {
		return true
	}

	return false
}

// SetDeactivatedAt gets a reference to the given float32 and assigns it to the DeactivatedAt field.
func (o *Organization) SetDeactivatedAt(v float32) {
	o.DeactivatedAt = &v
}

// GetServiceCount returns the ServiceCount field value if set, zero value otherwise.
func (o *Organization) GetServiceCount() float32 {
	if o == nil || o.ServiceCount == nil {
		var ret float32
		return ret
	}
	return *o.ServiceCount
}

// GetServiceCountOk returns a tuple with the ServiceCount field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetServiceCountOk() (float32, bool) {
	if o == nil || o.ServiceCount == nil {
		var ret float32
		return ret, false
	}
	return *o.ServiceCount, true
}

// HasServiceCount returns a boolean if a field has been set.
func (o *Organization) HasServiceCount() bool {
	if o != nil && o.ServiceCount != nil {
		return true
	}

	return false
}

// SetServiceCount gets a reference to the given float32 and assigns it to the ServiceCount field.
func (o *Organization) SetServiceCount(v float32) {
	o.ServiceCount = &v
}

// GetServiceCountTcp returns the ServiceCountTcp field value if set, zero value otherwise.
func (o *Organization) GetServiceCountTcp() float32 {
	if o == nil || o.ServiceCountTcp == nil {
		var ret float32
		return ret
	}
	return *o.ServiceCountTcp
}

// GetServiceCountTcpOk returns a tuple with the ServiceCountTcp field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetServiceCountTcpOk() (float32, bool) {
	if o == nil || o.ServiceCountTcp == nil {
		var ret float32
		return ret, false
	}
	return *o.ServiceCountTcp, true
}

// HasServiceCountTcp returns a boolean if a field has been set.
func (o *Organization) HasServiceCountTcp() bool {
	if o != nil && o.ServiceCountTcp != nil {
		return true
	}

	return false
}

// SetServiceCountTcp gets a reference to the given float32 and assigns it to the ServiceCountTcp field.
func (o *Organization) SetServiceCountTcp(v float32) {
	o.ServiceCountTcp = &v
}

// GetServiceCountUdp returns the ServiceCountUdp field value if set, zero value otherwise.
func (o *Organization) GetServiceCountUdp() float32 {
	if o == nil || o.ServiceCountUdp == nil {
		var ret float32
		return ret
	}
	return *o.ServiceCountUdp
}

// GetServiceCountUdpOk returns a tuple with the ServiceCountUdp field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetServiceCountUdpOk() (float32, bool) {
	if o == nil || o.ServiceCountUdp == nil {
		var ret float32
		return ret, false
	}
	return *o.ServiceCountUdp, true
}

// HasServiceCountUdp returns a boolean if a field has been set.
func (o *Organization) HasServiceCountUdp() bool {
	if o != nil && o.ServiceCountUdp != nil {
		return true
	}

	return false
}

// SetServiceCountUdp gets a reference to the given float32 and assigns it to the ServiceCountUdp field.
func (o *Organization) SetServiceCountUdp(v float32) {
	o.ServiceCountUdp = &v
}

// GetServiceCountArp returns the ServiceCountArp field value if set, zero value otherwise.
func (o *Organization) GetServiceCountArp() float32 {
	if o == nil || o.ServiceCountArp == nil {
		var ret float32
		return ret
	}
	return *o.ServiceCountArp
}

// GetServiceCountArpOk returns a tuple with the ServiceCountArp field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetServiceCountArpOk() (float32, bool) {
	if o == nil || o.ServiceCountArp == nil {
		var ret float32
		return ret, false
	}
	return *o.ServiceCountArp, true
}

// HasServiceCountArp returns a boolean if a field has been set.
func (o *Organization) HasServiceCountArp() bool {
	if o != nil && o.ServiceCountArp != nil {
		return true
	}

	return false
}

// SetServiceCountArp gets a reference to the given float32 and assigns it to the ServiceCountArp field.
func (o *Organization) SetServiceCountArp(v float32) {
	o.ServiceCountArp = &v
}

// GetServiceCountIcmp returns the ServiceCountIcmp field value if set, zero value otherwise.
func (o *Organization) GetServiceCountIcmp() float32 {
	if o == nil || o.ServiceCountIcmp == nil {
		var ret float32
		return ret
	}
	return *o.ServiceCountIcmp
}

// GetServiceCountIcmpOk returns a tuple with the ServiceCountIcmp field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetServiceCountIcmpOk() (float32, bool) {
	if o == nil || o.ServiceCountIcmp == nil {
		var ret float32
		return ret, false
	}
	return *o.ServiceCountIcmp, true
}

// HasServiceCountIcmp returns a boolean if a field has been set.
func (o *Organization) HasServiceCountIcmp() bool {
	if o != nil && o.ServiceCountIcmp != nil {
		return true
	}

	return false
}

// SetServiceCountIcmp gets a reference to the given float32 and assigns it to the ServiceCountIcmp field.
func (o *Organization) SetServiceCountIcmp(v float32) {
	o.ServiceCountIcmp = &v
}

// GetAssetCount returns the AssetCount field value if set, zero value otherwise.
func (o *Organization) GetAssetCount() float32 {
	if o == nil || o.AssetCount == nil {
		var ret float32
		return ret
	}
	return *o.AssetCount
}

// GetAssetCountOk returns a tuple with the AssetCount field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetAssetCountOk() (float32, bool) {
	if o == nil || o.AssetCount == nil {
		var ret float32
		return ret, false
	}
	return *o.AssetCount, true
}

// HasAssetCount returns a boolean if a field has been set.
func (o *Organization) HasAssetCount() bool {
	if o != nil && o.AssetCount != nil {
		return true
	}

	return false
}

// SetAssetCount gets a reference to the given float32 and assigns it to the AssetCount field.
func (o *Organization) SetAssetCount(v float32) {
	o.AssetCount = &v
}

// GetExportToken returns the ExportToken field value if set, zero value otherwise.
func (o *Organization) GetExportToken() string {
	if o == nil || o.ExportToken == nil {
		var ret string
		return ret
	}
	return *o.ExportToken
}

// GetExportTokenOk returns a tuple with the ExportToken field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetExportTokenOk() (string, bool) {
	if o == nil || o.ExportToken == nil {
		var ret string
		return ret, false
	}
	return *o.ExportToken, true
}

// HasExportToken returns a boolean if a field has been set.
func (o *Organization) HasExportToken() bool {
	if o != nil && o.ExportToken != nil {
		return true
	}

	return false
}

// SetExportToken gets a reference to the given string and assigns it to the ExportToken field.
func (o *Organization) SetExportToken(v string) {
	o.ExportToken = &v
}

// GetExportTokenCreatedAt returns the ExportTokenCreatedAt field value if set, zero value otherwise.
func (o *Organization) GetExportTokenCreatedAt() float32 {
	if o == nil || o.ExportTokenCreatedAt == nil {
		var ret float32
		return ret
	}
	return *o.ExportTokenCreatedAt
}

// GetExportTokenCreatedAtOk returns a tuple with the ExportTokenCreatedAt field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetExportTokenCreatedAtOk() (float32, bool) {
	if o == nil || o.ExportTokenCreatedAt == nil {
		var ret float32
		return ret, false
	}
	return *o.ExportTokenCreatedAt, true
}

// HasExportTokenCreatedAt returns a boolean if a field has been set.
func (o *Organization) HasExportTokenCreatedAt() bool {
	if o != nil && o.ExportTokenCreatedAt != nil {
		return true
	}

	return false
}

// SetExportTokenCreatedAt gets a reference to the given float32 and assigns it to the ExportTokenCreatedAt field.
func (o *Organization) SetExportTokenCreatedAt(v float32) {
	o.ExportTokenCreatedAt = &v
}

// GetExportTokenLastUsedAt returns the ExportTokenLastUsedAt field value if set, zero value otherwise.
func (o *Organization) GetExportTokenLastUsedAt() float32 {
	if o == nil || o.ExportTokenLastUsedAt == nil {
		var ret float32
		return ret
	}
	return *o.ExportTokenLastUsedAt
}

// GetExportTokenLastUsedAtOk returns a tuple with the ExportTokenLastUsedAt field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetExportTokenLastUsedAtOk() (float32, bool) {
	if o == nil || o.ExportTokenLastUsedAt == nil {
		var ret float32
		return ret, false
	}
	return *o.ExportTokenLastUsedAt, true
}

// HasExportTokenLastUsedAt returns a boolean if a field has been set.
func (o *Organization) HasExportTokenLastUsedAt() bool {
	if o != nil && o.ExportTokenLastUsedAt != nil {
		return true
	}

	return false
}

// SetExportTokenLastUsedAt gets a reference to the given float32 and assigns it to the ExportTokenLastUsedAt field.
func (o *Organization) SetExportTokenLastUsedAt(v float32) {
	o.ExportTokenLastUsedAt = &v
}

// GetExportTokenLastUsedBy returns the ExportTokenLastUsedBy field value if set, zero value otherwise.
func (o *Organization) GetExportTokenLastUsedBy() string {
	if o == nil || o.ExportTokenLastUsedBy == nil {
		var ret string
		return ret
	}
	return *o.ExportTokenLastUsedBy
}

// GetExportTokenLastUsedByOk returns a tuple with the ExportTokenLastUsedBy field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetExportTokenLastUsedByOk() (string, bool) {
	if o == nil || o.ExportTokenLastUsedBy == nil {
		var ret string
		return ret, false
	}
	return *o.ExportTokenLastUsedBy, true
}

// HasExportTokenLastUsedBy returns a boolean if a field has been set.
func (o *Organization) HasExportTokenLastUsedBy() bool {
	if o != nil && o.ExportTokenLastUsedBy != nil {
		return true
	}

	return false
}

// SetExportTokenLastUsedBy gets a reference to the given string and assigns it to the ExportTokenLastUsedBy field.
func (o *Organization) SetExportTokenLastUsedBy(v string) {
	o.ExportTokenLastUsedBy = &v
}

// GetExportTokenCounter returns the ExportTokenCounter field value if set, zero value otherwise.
func (o *Organization) GetExportTokenCounter() float32 {
	if o == nil || o.ExportTokenCounter == nil {
		var ret float32
		return ret
	}
	return *o.ExportTokenCounter
}

// GetExportTokenCounterOk returns a tuple with the ExportTokenCounter field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetExportTokenCounterOk() (float32, bool) {
	if o == nil || o.ExportTokenCounter == nil {
		var ret float32
		return ret, false
	}
	return *o.ExportTokenCounter, true
}

// HasExportTokenCounter returns a boolean if a field has been set.
func (o *Organization) HasExportTokenCounter() bool {
	if o != nil && o.ExportTokenCounter != nil {
		return true
	}

	return false
}

// SetExportTokenCounter gets a reference to the given float32 and assigns it to the ExportTokenCounter field.
func (o *Organization) SetExportTokenCounter(v float32) {
	o.ExportTokenCounter = &v
}

type NullableOrganization struct {
	Value        Organization
	ExplicitNull bool
}

func (v NullableOrganization) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableOrganization) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
